events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 8080;
    root /app/public;
    index index.php index.html;
    client_max_body_size 256m;

    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }

    location /sites/ {
      try_files $uri $uri/ /sites/index.php?$query_string;
    }

    location ~ \.php$ {
      try_files $uri =404;
      include /etc/nginx/fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_pass legacy-php:9000;
      fastcgi_read_timeout 300s;
    }
  }
}
