const test=require('node:test'),assert=require('node:assert/strict'),T=require('../public/measure/internal/editor_scripts/wall_steps.js'),F=require('../public/measure/internal/editor_scripts/wall_base_binding.js'),K=require('../public/measure/internal/editor_scripts/exterior_geometry.js'),G=require('../public/measure/internal/editor_scripts/wall_geometry.js');
const p=(x,y,z=0)=>({x,y,z}),base=()=>({faces:[{id:'base',points:[p(0,0),p(12,0,3),p(12,8,3),p(0,8)]}]});
test('base steps cover the exact footprint with equal rise and horizontal terraces in either slope direction',()=>{for(const sign of [-1,1]){const b=base();b.faces[0].points.forEach(p=>p.z*=sign);const original=JSON.stringify(b),r=T.basePattern(b,'base',2);assert.equal(JSON.stringify(b),original);assert.equal(r.base.faces.length,3);assert.ok(Math.abs(r.base.faces.reduce((n,f)=>n+K.area(f),0)-96)<1e-6);for(const f of r.base.faces)assert.ok(f.points.every(p=>p.z===f.points[0].z));assert.equal(new Set(r.base.faces.map(f=>f.points[0].z)).size,3);}});
test('base pattern can be reopened after saving and an indentation without resurrecting the old footprint',()=>{const first=T.basePattern(base(),'base',2).base,loaded=JSON.parse(JSON.stringify(first));loaded.faces.forEach(f=>f.points.forEach(p=>{if(p.y===0)p.y=1;}));const next=T.basePattern(loaded,loaded.faces[1].id,4,.4).base;assert.equal(next.faces.length,5);assert.ok(next.faces.flatMap(f=>f.points).every(p=>p.y>=1));assert.ok(Math.abs(next.faces.reduce((n,f)=>n+K.area(f),0)-84)<1e-6);});
test('walls inherit base steps while an explicit line pattern keeps its own baseline',()=>{const b=base(),wall={id:'front',points:[p(0,0),p(12,0,3),p(12,0,6),p(0,0,6)]},other={...structuredClone(wall),id:'back',points:wall.points.map(p=>({...p,y:8}))};const custom=T.pattern(wall.points.slice(0,2),{n:{x:0,y:-1,z:0}},3),overridden=T.apply([wall],custom).faces[0];const result=F.follow({$surfaces:[overridden,other]},b,T.basePattern(b,'base',1).base);assert.deepEqual(result.$surfaces[0],overridden);assert.ok(result.$surfaces[1].points.length>4);assert.deepEqual(result.$surfaces[1].points.filter(p=>p.z===6),other.points.filter(p=>p.z===6));});
test('flat bases report how to establish a slope and preserve input',()=>{const b=base();b.faces[0].points.forEach(p=>p.z=0);assert.throws(()=>T.basePattern(b,'base'),/Pitch the base first/);assert.equal(b.faces.length,1);});
test('near-axis grades on rotated foundations produce square risers; deliberate diagonal grades stay diagonal',()=>{
 const angle=42.815*Math.PI/180,u={x:Math.cos(angle),y:Math.sin(angle)};
 const make=degrees=>({faces:[{id:'rotated',points:[[0,0],[12,0],[12,8],[0,8]].map(([x,y])=>{const p={x:u.x*x-u.y*y,y:u.y*x+u.x*y};return {...p,z:150+.3*(p.x*Math.cos(degrees*Math.PI/180)+p.y*Math.sin(degrees*Math.PI/180))};})}]});
 const b=make(45),result=T.basePattern(b,'rotated',3,.4,.7);
 assert.equal(result.alignedToBoundary,true);assert.ok(Math.abs(result.pattern.horizontal.x*u.y-result.pattern.horizontal.y*u.x)<1e-9);
 assert.ok(Math.abs(result.base.faces.reduce((sum,f)=>sum+K.area(f),0)-96)<1e-5);
 for(const f of result.base.faces)assert.ok(f.points.every(p=>p.z===f.points[0].z));
 const free=T.basePattern(b,'rotated',3,null,1,{alignToBoundary:false});assert.ok(Math.abs(Math.abs(free.pattern.horizontal.x)-Math.SQRT1_2)<1e-9);
 const diagonal=T.basePattern(make(60),'rotated',3);assert.equal(diagonal.alignedToBoundary,false);
});

 test('resized base treads retain area and saved width metadata',()=>{for(const scale of [.1,.7,1.4,20]){const r=T.basePattern(base(),'base',3,.37,scale);assert.equal(r.base.faces.length,4);assert.ok(Math.abs(r.base.faces.reduce((n,f)=>n+K.area(f),0)-96)<1e-6);assert.equal(r.base.stepPatterns.base.sizeScale,scale);}});

test('base resizing preserves the plan position of original user anchors and wall attachments',()=>{const S=require('../public/measure/internal/editor_scripts/base_sketch_geometry.js'),b=base();const anchor=p(4.3,0,4.3/4);S.add(b,anchor,.00001);const node=b.sketch.nodes.find(n=>Math.abs(n.x-anchor.x)<1e-6&&n.y===0);node.userDraftPoint=true;const wall={id:'front',points:[p(0,0),p(12,0,3),p(12,0,6),p(0,0,6)],retainedPoints:[{...anchor,anchorId:'original'}]};for(const size of [.7,.9999,1,1.0001,1.2]){const result=T.basePattern(b,'base',4,.4,size),q=result.base.sketch.nodes.find(n=>n.id===node.id);assert.ok(q);assert.equal(q.x,anchor.x);assert.equal(q.y,anchor.y);const attached=F.follow({$surfaces:[wall]},b,result.base).$surfaces[0].retainedPoints.find(p=>p.anchorId==='original');assert.ok(attached);assert.ok(Math.abs(attached.x-anchor.x)<1e-6);assert.equal(attached.y,anchor.y);}});
