const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('../public/v1/node_modules/playwright-core');
test('persistent rendering preserves movement, opening cuts, cancellation and selection across real WebGL frames',async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':'/usr/bin/chromium',args:['--no-sandbox','--use-angle=swiftshader']});
 try{const page=await browser.newPage({viewport:{width:1000,height:700}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent('<canvas id="view"></canvas>');
 await page.addScriptTag({path:'public/v1/node_modules/three/build/three.min.js'});
 for(const name of ['vendor/clipper-lib-6.4.2-clipper','vendor/earcut-3.2.3-earcut.dev','exterior_geometry','base_geometry','base_sketch_geometry','wall_geometry','wall_solid_geometry','wall_features','exterior_model','wall_chimneys','wall_editor','wall_face_draft','exterior_scene_cache','exterior_frame_pipeline'])await page.addScriptTag({path:'public/measure/internal/editor_scripts/'+name+'.js'});
 const result=await page.evaluate(async()=>{
  const rect=(x,z,w,h)=>[{x,y:0,z},{x:x+w,y:0,z},{x:x+w,y:0,z:z+h},{x,y:0,z:z+h}],input={wallEdits:{$surfaces:[{id:'host',points:rect(0,0,60,4)},...Array.from({length:20},(_,i)=>({id:'window-'+i,points:rect(1+i*3,1,1.2,1.5),feature:{type:'window',axis:{x:1,y:0,z:0}}}))]}};
  const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('canvas'),antialias:true});renderer.setSize(1000,700);const camera=new THREE.PerspectiveCamera(45,1000/700,.01,200);camera.position.set(30,6,70);camera.lookAt(30,2,0);camera.updateMatrixWorld();window.camera=camera;window.renderer=renderer;window.getVector3=p=>new THREE.Vector3(p.x,p.z,-p.y);
  const vector=window.getVector3,dispose=root=>root?.traverse(o=>{o.geometry?.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]).filter(Boolean))m.dispose();});
  function setup(reuse){const state=structuredClone(input),scene=new THREE.Scene(),cache=new ExteriorSceneCache();let previous=null;
   const e=(x,y)=>({clientX:x*100,clientY:y*100,button:0,buttons:1,target:{closest:s=>s==='#three-view-wrapper'},preventDefault(){},stopImmediatePropagation(){}});
   const editor=createWallFaceDraft({state:()=>state,walls:()=>[],active:()=>true,selected:()=>null,toPixel:p=>p,screen:p=>({x:p.x*100,y:p.z*100}),projectPoint:(d,event)=>d.frame?WallSolidGeometry.inFrame(d.frame,{x:event.clientX/100,y:0,z:event.clientY/100}):{x:event.clientX/100,y:event.clientY/100,z:0},redraw(){},message(){},commit(){}});
   const draw=()=>{window.WallMode={renderChunk:(key,input,parent,build)=>reuse?cache.part(key,input,parent,build):build(parent)};const next=new THREE.Group();cache.begin(window.testMode||'translucent');editor.draw3D(next,vector);exteriorSurfaceDisplay(next,window.testMode||'translucent');scene.add(next);const stats=cache.commit();if(previous){scene.remove(previous);dispose(previous);}previous=next;renderer.render(scene,camera);const objects=[];next.traverse(o=>{if(o.isMesh&&!o.isSprite)objects.push({id:o.userData.solidId,points:Array.from(o.geometry.attributes.position.array),index:o.geometry.index&&Array.from(o.geometry.index.array),selected:!!o.userData.exteriorSelected});});return {objects,stats};};
   draw();editor.geometryCommand('m',{points:input.wallEdits.$surfaces[1].points,event:e(1.6,1.75)});return {state,editor,draw,scene,cache};
  }
  const a=setup(true),b=setup(false),snapshots=[],times=[];for(let i=0;i<12;i++){window.testMode=i<6?'translucent':'opaque';const amount=.05*(i+1);let start=performance.now();a.editor.distanceInput().set(amount);const cached=a.draw();const cachedMs=performance.now()-start;start=performance.now();b.editor.distanceInput().set(amount);const full=b.draw();const fullMs=performance.now()-start;snapshots.push({same:JSON.stringify(cached.objects)===JSON.stringify(full.objects),reused:cached.stats.reused,built:cached.stats.built,sameModel:JSON.stringify(a.state)===JSON.stringify(b.state)});times.push({cachedMs,fullMs});await new Promise(requestAnimationFrame);}
  a.editor.key({key:'escape'});b.editor.key({key:'escape'});const cancel=JSON.stringify(a.draw().objects)===JSON.stringify(b.draw().objects);renderer.dispose();return {snapshots,cancel,times};
 });
 assert.ok(result.snapshots.every(s=>s.same&&s.sameModel),JSON.stringify(result.snapshots));assert.ok(result.snapshots.filter((_,i)=>i!==0&&i!==6).every(s=>s.reused>=19),JSON.stringify(result.snapshots));assert.ok(result.cancel);assert.deepEqual(errors,[]);console.log('WebGL movement samples:',JSON.stringify(result.times.slice(3)));
 }finally{await browser.close();}
});
