const {chromium}=require('../public/v1/node_modules/playwright-core'),fs=require('fs'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const page=await browser.newPage({viewport:{width:1600,height:1100}}),uploads=[];await page.route('http://127.0.0.1:8031/**',async route=>{if(route.request().method()==='GET')return route.fulfill({contentType:'text/html',body:'<main style="font:16px system-ui"><h1>Full-house measurements</h1><div id="order-references"></div></main>'});const req=route.request(),bytes=req.postDataBuffer(),name=new URL(req.url()).searchParams.get('name');uploads.push({name,headers:req.headers(),bytes});return route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,sha256:createHash('sha256').update(bytes).digest('hex')})});});await page.goto('http://127.0.0.1:8031/reference-test');await page.addScriptTag({path:'public/measure/internal/portal_scripts/full_house_references.js'});const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1ioAAAAASUVORK5CYII=','base64');const slots=['front','back','left','right','front-left','front-right','back-left','back-right'];await page.locator('#order-reference-photos').setInputFiles([...slots.map(slot=>({name:slot+'.png',mimeType:'image/png',buffer:png})),{name:'detail.png',mimeType:'image/png',buffer:png},{name:'another.png',mimeType:'image/png',buffer:png}]);
assert.equal(await page.locator('.reference-card').count(),10);
const photo=name=>page.locator('.reference-card').filter({has:page.getByRole('button',{name:'Select '+name,exact:true})}).locator('.reference-photo');
const target=slot=>page.locator('[data-slot="'+slot+'"]');
for(const slot of slots)await photo(slot+'.png').dragTo(target(slot));
assert.equal(await page.locator('.reference-slot.assigned').count(),8);
await target('front').locator('.reference-target').dragTo(target('back'));
assert.equal(await target('front').locator('img').getAttribute('alt'),'back.png');
await target('back').locator('.reference-target').dragTo(target('front'));
await photo('detail.png').dragTo(target('front'));
assert.equal(await target('front').locator('img').getAttribute('alt'),'detail.png');
await photo('front.png').click();await target('front').locator('.reference-target').click();
assert.equal(await target('front').locator('img').getAttribute('alt'),'front.png');
await target('left').locator('.reference-target').dragTo(page.locator('.reference-bank-header'));
assert.equal(await target('left').locator('img').count(),0);
await photo('left.png').dragTo(target('left'));
await page.locator('#order-reference-photos').setInputFiles({name:'reject.txt',mimeType:'text/plain',buffer:Buffer.from('x')});
assert.equal(await page.locator('.reference-card').count(),10);
assert.match(await page.locator('.reference-error').textContent(),/skipped/);
await page.evaluate(()=>FullHouseReferences.lock(true));
assert.equal(await page.locator('.reference-target:disabled').count(),8);assert.equal(await page.locator('.reference-photo[draggable=true]').count(),0);
await page.evaluate(()=>FullHouseReferences.lock(false));
await page.locator('#order-reference-video').setInputFiles({name:'walkthrough.webm',mimeType:'video/webm',buffer:Buffer.alloc(9*1024*1024,1)});assert.ok((await page.locator('.reference-bank').boundingBox()).x>(await page.locator('.reference-board').boundingBox()).x+600,'bank is beside board on desktop');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'tmp/pdfs/order-references-ui.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile has no horizontal overflow');await page.setViewportSize({width:1600,height:1100});await page.evaluate(()=>FullHouseReferences.upload('fullhouse_'+'a'.repeat(32),'test-csrf',()=>{}));const indices=uploads.filter(u=>u.name.startsWith('internal-resource-v2')).map(u=>JSON.parse(u.bytes));assert.equal(indices.length,11);assert.deepEqual(indices.filter(i=>i.elevation_view).map(i=>i.elevation_view),slots);assert.equal(indices.find(i=>i.original_name==='walkthrough.webm').parts,2);assert.ok(uploads.every(u=>u.headers['x-resource-origin']==='customer-order'&&u.headers['x-full-house-csrf']==='test-csrf'));const count=uploads.length;await page.evaluate(()=>FullHouseReferences.upload('fullhouse_'+'a'.repeat(32),'test-csrf',()=>{}));assert.equal(uploads.length,count);console.log(JSON.stringify({photos:10,videoParts:2,published:indices.length,retryDuplicates:0}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
