const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('../public/v1/node_modules/playwright-core');
test('Resources restores the open file and drawers and shares only Tech uploads with submission',async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':'/usr/bin/chromium'),args:['--no-sandbox']});
 try{
  const page=await browser.newPage({viewport:{width:1300,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const names=['internal-resource-v2-aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa-front.png','internal-resource-v2-bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb-qa.png'];
  let savedMarkup;const files=names.map((name,i)=>({name,original_name:i?'QA.png':'Front.png',role:i?'qa':'tech',size:100}));
  const css=fs.readFileSync('public/measure/internal/editor_scripts/project_resources.css','utf8'),script=fs.readFileSync('public/measure/internal/editor_scripts/project_resources.js','utf8');
  const wall=fs.readFileSync('public/measure/internal/editor_scripts/wall_mode.js','utf8'),historyRouting=wall.slice(wall.indexOf('function handleEditorKey(e){')+'function handleEditorKey(e){'.length,wall.indexOf('if(!enabled)return;',wall.indexOf('function handleEditorKey(e){')));
  const html=`<style>#google-earth-wrapper{position:relative;width:1200px;height:800px}${css}</style><button id="model-view">Model view</button><div id="google-earth-wrapper"><div class="map-view-tabs"><button class="map-tab" onclick="switchMapLayer('map')">Map</button></div></div><script>window.currentProjectId='fixture';window.Resource3DOverlay={imageName:'',async show({name}){this.imageName=name;window.dispatchEvent(new Event('resource-3d-overlay-change'));},remove(){this.imageName='';window.dispatchEvent(new Event('resource-3d-overlay-change'));}};window.switchMapLayer=()=>{};window.firstMeasureBuildUrl=p=>p;window.modelUndo=0;window.addEventListener('keydown',e=>{${historyRouting}if(e.ctrlKey&&['z','y'].includes(e.key)){window.modelUndo++;e.preventDefault();}},true);</script><script>${script}</script>`;
  await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.pathname.endsWith('project_resources.php')){if(route.request().method()==='POST'){const name=u.searchParams.get('name');if(name.startsWith('internal-resource-v2-')){const index=JSON.parse(route.request().postData());files.push({name,original_name:index.original_name,role:route.request().headers()['x-resource-role'],size:index.size});}return route.fulfill({json:{ok:true,sha256:route.request().headers()['x-resource-sha256']}});}if(u.searchParams.has('name'))return route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});return route.fulfill({json:{files}});}if(u.searchParams.get('action')==='project_feedback')return route.fulfill({json:{manifest:{tech_notes:'Customer instruction'}}});return route.fulfill({contentType:'text/html',body:html});});
  await page.goto('https://resources.test/editor.php');await page.getByRole('button',{name:'Resources',exact:true}).click();await page.getByText('Front.png',{exact:true}).click();await page.locator('#project-resources canvas').waitFor({state:'visible'});
  const tech=page.locator('.resource-section[data-role="tech"]'),qa=page.locator('.resource-section[data-role="qa"]');
  assert.ok((await tech.locator('.resource-item').first().boundingBox()).height<=30);assert.equal(await page.locator('.resource-item small').count(),0);
  const overlay=tech.locator('.resource-overlay-shortcut');await overlay.click();await page.waitForFunction(()=>document.querySelector('.resource-section[data-role=tech] .resource-overlay-shortcut')?.getAttribute('aria-pressed')==='true');assert.equal(await overlay.getAttribute('aria-pressed'),'true');await overlay.click();assert.equal(await overlay.getAttribute('aria-pressed'),'false');
  await tech.locator('summary').click();assert.equal(await tech.locator('.resource-item').isVisible(),false);await tech.locator('summary').click();
  await qa.locator('summary').click();
  assert.equal(await page.getByText('Tech (You)',{exact:true}).count(),1);await page.locator('[data-action="notes"]').click();await page.waitForTimeout(800);await page.reload();await page.locator('#project-resources canvas').waitFor({state:'visible'});assert.match(await page.locator('.resource-filename').textContent(),/Front.png/);assert.equal(await page.locator('.resource-notes-pane').isVisible(),true);assert.equal(await qa.evaluate(el=>el.open),false);await qa.locator('summary').click();
  const result=await page.evaluate(async()=>{const state={folderId:'fixture',finalizeSources:{images:[],notes:'Existing'}};await ProjectResources.mergeSubmission(state);await ProjectResources.mergeSubmission(state);return state;});assert.equal(result.finalizeSources.images.length,1);assert.equal(result.finalizeSources.images[0].resource_name,names[0]);assert.equal(result.finalizeSources.notes,'Existing');
  page.on('request',request=>{if(request.method()==='POST'&&/internal-markup-[a-f0-9-]+-/.test(request.url())&&!request.url().includes('internal-markup-part-'))savedMarkup=JSON.parse(request.postData());});
  const drag=async()=>{const b=await page.locator('.resource-stage').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+30,b.y+b.height/2+20,{steps:4});await page.mouse.up();};
  await page.locator('[data-action="markup"]').click();assert.equal(await page.locator('[data-tool="pen"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('select.resource-width').count(),0);
  await page.getByRole('button',{name:'Thin stroke',exact:true}).click();await drag();await page.locator('[data-action="save"]').click();await page.locator('[data-action="save"]').waitFor({state:'hidden'});assert.equal(savedMarkup.marks.length,1);assert.equal(savedMarkup.marks[0].type,'pen');const thin=savedMarkup.marks[0].width;
  await page.locator('[data-action="closeInspector"]').click();await drag();assert.equal(await page.locator('[data-action="save"]').isVisible(),false,'closing markup pans without making marks');
  await page.locator('[data-action="markup"]').click();await page.locator('[data-tool="pen"]').click();assert.equal(await page.locator('[data-tool="pen"]').getAttribute('aria-pressed'),'false');await drag();assert.equal(await page.locator('[data-action="save"]').isVisible(),false,'deselected tools pan');
  await page.locator('[data-tool="line"]').click();await page.getByRole('button',{name:'Thick stroke',exact:true}).click();await drag();await page.locator('[data-action="save"]').click();await page.locator('[data-action="save"]').waitFor({state:'hidden'});assert.equal(savedMarkup.marks.length,2);assert.equal(savedMarkup.marks[1].type,'line');assert.ok(Math.abs(savedMarkup.marks[1].width/thin-4)<1e-8);
  await page.keyboard.press('Control+z');await page.locator('[data-action="save"]').click();await page.locator('[data-action="save"]').waitFor({state:'hidden'});assert.equal(savedMarkup.marks.length,1);assert.equal(await page.evaluate(()=>modelUndo),0);
  await page.keyboard.press('Control+y');await page.locator('[data-action="save"]').click();await page.locator('[data-action="save"]').waitFor({state:'hidden'});assert.equal(savedMarkup.marks.length,2);assert.equal(await page.evaluate(()=>modelUndo),0);
  await page.locator('#model-view').click();await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>modelUndo),1);assert.equal(await page.locator('[data-action="save"]').isVisible(),false,'model focus leaves Resources history unchanged');
  await page.locator('.resource-stage').focus();
  for(const [key,tool]of Object.entries({c:'circle',a:'arrow',p:'pen',l:'line',b:'rect',s:'select',t:'note'})){await page.keyboard.press(key);assert.equal(await page.locator('[data-tool="'+tool+'"]').getAttribute('aria-pressed'),'true');}
  const text=page.locator('.resource-note input');await text.fill('');await page.keyboard.type('caplbts');assert.equal(await text.inputValue(),'caplbts');assert.equal(await page.locator('[data-tool="note"]').getAttribute('aria-pressed'),'true','typing never switches tools');
  await page.locator('.resource-stage').focus();await page.keyboard.press('s');await page.keyboard.press('s');assert.equal(await page.locator('[data-tool="select"]').getAttribute('aria-pressed'),'true','repeating a shortcut keeps its tool selected');
  const stageBox=await page.locator('.resource-stage').boundingBox();await page.mouse.click(stageBox.x+stageBox.width/2+15,stageBox.y+stageBox.height/2+10);assert.equal(await page.locator('[data-action="delete"]').isEnabled(),true);
  await page.getByRole('button',{name:'Thick stroke',exact:true}).focus();await page.keyboard.press('Delete');assert.equal(await page.locator('[data-action="delete"]').isEnabled(),false);await page.locator('[data-action="save"]').click();await page.locator('[data-action="save"]').waitFor({state:'hidden'});assert.equal(savedMarkup.marks.length,1,'Delete works from a focused markup control');
  await page.keyboard.press('Control+z');await page.locator('[data-action="save"]').click();await page.locator('[data-action="save"]').waitFor({state:'hidden'});assert.equal(savedMarkup.marks.length,2,'keyboard deletion is undoable');
  await page.locator('[data-action="notes"]').click();assert.equal(await page.locator('[data-tool="line"]').getAttribute('aria-pressed'),'false');await drag();assert.equal(await page.locator('[data-action="save"]').isVisible(),false);
  await page.getByRole('button',{name:'Map',exact:true}).click();await page.reload();await page.waitForTimeout(900);assert.equal(await page.locator('#project-resources').isVisible(),false);assert.deepEqual(errors,[]);
  await page.goto('https://resources.test/editor.php?qa_embed=1');await page.getByRole('button',{name:'Resources',exact:true}).click();await page.getByText('QA (You)',{exact:true}).waitFor();await page.locator('.resource-files').setInputFiles({name:'QA-reference.txt',mimeType:'text/plain',buffer:Buffer.from('QA guidance')});await page.getByText('QA-reference.txt',{exact:true}).waitFor();assert.equal(files.at(-1).role,'qa');
 }finally{await browser.close();}
});
