const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('../public/v1/node_modules/playwright-core');
test('frame images expose direct video jumps in the viewer and file list after reload',async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':'/usr/bin/chromium'),args:['--no-sandbox']});
 try{
  const page=await browser.newPage(),video='internal-resource-video.webm',frame='internal-resource-v2-aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa-frame.png',capture='internal-resource-v2-bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb-capture.png',favorite='internal-markup-favorite-test.json',markup='internal-markup-bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb-123.json';
  const files=[{name:video,original_name:'Walkthrough.webm'},{name:frame,original_name:'Front.png'},{name:capture,original_name:'Capture.png'},{name:favorite},{name:markup}];
  const records={[favorite]:{version:1,label:'Front',source:video,frame,time:.25},[markup]:{sourceVideo:{name:video,time:.5}}};
  const script=fs.readFileSync('public/measure/internal/editor_scripts/project_resources.js','utf8'),css=fs.readFileSync('public/measure/internal/editor_scripts/project_resources.css','utf8');
  await page.route('**/*',route=>{const u=new URL(route.request().url()),name=u.searchParams.get('name');if(u.pathname.endsWith('project_resources.php')){if(route.request().method()==='POST'){if(name.startsWith('internal-markup-favorite-')){records[name]=JSON.parse(route.request().postData());if(!files.some(f=>f.name===name))files.push({name});}else if(name.startsWith('internal-resource-v2-')){const index=JSON.parse(route.request().postData());files.push({name,original_name:index.original_name});}return route.fulfill({json:{ok:true,sha256:route.request().headers()['x-resource-sha256']}});}if(records[name])return route.fulfill({json:records[name]});if(name===video){const bytes=fs.readFileSync('dev/fixtures/resources-landscape.webm'),range=route.request().headers().range?.match(/bytes=(\d+)-(\d*)/),start=range?Number(range[1]):0,end=range&&range[2]?Math.min(Number(range[2]),bytes.length-1):bytes.length-1;return route.fulfill({status:range?206:200,contentType:'video/webm',headers:{'Accept-Ranges':'bytes',...(range?{'Content-Range':'bytes '+start+'-'+end+'/'+bytes.length}:{})},body:bytes.subarray(start,end+1)});}if(name)return route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});return route.fulfill({json:{files}});}if(u.searchParams.has('action'))return route.fulfill({json:{manifest:{}}});return route.fulfill({contentType:'text/html',body:`<style>#google-earth-wrapper{position:relative;width:1000px;height:700px}${css}</style><div id="google-earth-wrapper"><div class="map-view-tabs"></div></div><script>currentProjectId='fixture';switchMapLayer=()=>{};</script><script>${script}</script>`});});
  await page.goto('https://frames.test/editor.php');await page.getByRole('button',{name:'Resources',exact:true}).click();await page.getByText('Front.png',{exact:true}).click();await page.locator('canvas').waitFor({state:'visible'});
  const jump=page.getByRole('button',{name:'Jump to video frame',exact:true});assert.equal(await jump.isVisible(),true);const j=await jump.boundingBox(),zoom=await page.locator('.resource-view-controls').boundingBox();assert.ok(j.y+j.height<=zoom.y,'jump sits above zoom controls');
  await jump.click();await page.waitForFunction(()=>document.querySelector('video')?.currentTime>=.24);assert.equal(await jump.isVisible(),false);
  await page.getByText('Capture.png',{exact:true}).click();await page.locator('canvas').waitFor({state:'visible'});await page.waitForTimeout(750);await page.reload();await jump.waitFor({state:'visible'});
  await page.getByRole('button',{name:'Jump to video frame for Capture.png',exact:true}).click();await page.waitForFunction(()=>document.querySelector('video')?.currentTime>=.49);
  await page.getByRole('button',{name:'Jump to video frame for Front.png',exact:true}).click();await page.waitForFunction(()=>{const v=document.querySelector('video');return v&&Math.abs(v.currentTime-.25)<.05;});
  assert.equal(await page.getByRole('button',{name:'Saved Frame',exact:true}).isVisible(),true);
  await page.getByRole('button',{name:'Saved Frame',exact:true}).click();await page.locator('canvas').waitFor({state:'visible'});await jump.click();await page.waitForFunction(()=>{const v=document.querySelector('video');return v?.readyState>=2&&Math.abs(v.currentTime-.25)<.01;});await page.locator('video').evaluate(v=>{v.currentTime=1.5;});await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2&&!document.querySelector('video').seeking);
  await page.getByRole('button',{name:'Save Frame',exact:true}).click();await page.getByRole('button',{name:'Saved Frame',exact:true}).waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('[data-action=returnVideo]').disabled);
  const saved=Object.entries(records).find(([key,r])=>key.startsWith('internal-markup-favorite-')&&r.time===1.5);assert.ok(saved);assert.equal(saved[1].label,'');assert.equal(await page.locator('.resource-favorite-entry').isVisible(),false);
  const title=page.locator('.resource-favorite-title').first();assert.equal(await title.evaluate(el=>document.activeElement===el),true);assert.equal(await title.getAttribute('data-frame'),saved[1].frame);await page.keyboard.type('Side window');await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.querySelector('video').paused);assert.equal(records[saved[0]].label,'Side window');assert.equal(await title.evaluate(el=>document.activeElement===el),false);
  await page.reload();await page.locator('.resource-favorite-title').first().waitFor();assert.equal(await page.locator('.resource-favorite-title').first().inputValue(),'Side window');
  await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);await page.locator('video').evaluate(v=>{v.pause();v.currentTime=.1;});await page.waitForFunction(()=>!document.querySelector('video').seeking);await page.getByRole('button',{name:'Save Frame',exact:true}).click();await page.waitForFunction(()=>document.activeElement?.matches('.resource-favorite-title')&&!document.querySelector('[data-action=returnVideo]').disabled);
  const latest=Object.values(records).find(r=>r.version===1&&Math.abs(r.time-.1)<.01);assert.ok(latest);assert.equal(await page.locator('.resource-favorite-title').first().getAttribute('data-frame'),latest.frame,'newly saved earlier video moment appears first');await page.keyboard.press('Space');await page.waitForFunction(()=>!document.querySelector('video').paused);assert.equal(await page.locator('.resource-favorite-title').first().evaluate(el=>document.activeElement===el),false);assert.equal(latest.label,'');
 }finally{await browser.close();}
});
