const test=require('node:test'),assert=require('node:assert/strict'),R=require('../public/measure/internal/editor_scripts/roof_trim.js');
const p=(x,y,z)=>({x,y,z}),a=p(0,0,3),b=p(6,0,3),c=p(6,2,4),d=p(0,2,4),e=p(6,4,3),f=p(0,4,3),roof={points:[a,b,c,d,e,f],connections:[[0,1,'eave'],[1,2,'rake'],[2,4,'rake'],[4,5,'eave'],[5,3,'rake'],[3,0,'rake'],[3,2,'ridge']].map(([startIdx,endIdx,type])=>({startIdx,endIdx,type})),faces:[{points:[a,b,c,d]},{points:[d,c,e,f]}]};
test('gable perimeter has six vertical six-inch panels and no ridge trim',()=>{const original=JSON.stringify(roof),panels=R.panels(roof);assert.equal(panels.length,6);assert.ok(panels.every(f=>Math.abs(f.height-.1524)<1e-10));assert.ok(!panels.some(f=>[f.a,f.b].every(p=>p.y===2)));for(const f of panels){assert.equal(f.material,'trim-horizontal');assert.deepEqual(f.points[0],f.a);assert.ok(Math.abs(f.points[0].z-f.points[3].z-.1524)<1e-10);assert.equal(f.points[0].x,f.points[3].x);assert.equal(f.points[0].y,f.points[3].y);}assert.equal(JSON.stringify(roof),original);});
test('collinear roof anchors and duplicate faces do not create duplicate trim',()=>{const mid=p(3,0,3),split={...roof,faces:[{points:[a,mid,b,c,d]},roof.faces[1],{points:[...roof.faces[1].points].reverse()}]};assert.equal(R.panels(split).length,6);assert.deepEqual(R.panels(split).map(p=>p.id),R.panels(roof).map(p=>p.id));});
test('a long edge shared with split neighboring faces is internal, including T-junctions',()=>{const center=p(3,2,4),rear=p(3,4,3),split={...roof,faces:[roof.faces[0],{points:[d,center,rear,f]},{points:[center,c,e,rear]}]};assert.equal(R.panels(split).length,6);assert.ok(!R.panels(split).some(f=>[f.a,f.b].every(p=>p.y===2)));});
test('multi-selection height, deletion and reload preserve roof geometry and unrelated sides',()=>{const panels=R.panels(roof),ids=panels.slice(0,2).map(f=>f.id),initial={};const taller=R.setHeight(initial,ids,9.5);assert.deepEqual(initial,{});const next=R.panels(roof,JSON.parse(JSON.stringify(taller)));assert.ok(next.filter(p=>ids.includes(p.id)).every(p=>Math.abs(p.height-9.5*.0254)<1e-9));assert.ok(next.filter(p=>!ids.includes(p.id)).every(p=>Math.abs(p.height-.1524)<1e-10));const deleted=R.setHeight(taller,[ids[0]],0);assert.equal(R.panels(roof,deleted).filter(f=>f.deleted).length,1);assert.equal(R.panels(roof,R.setHeight(deleted,[ids[0]],6)).filter(f=>f.deleted).length,0);assert.throws(()=>R.setHeight(initial,ids,-2));});

test('trim controller supports Shift selection, typed inches, Escape, Delete and undo snapshots',()=>{
 const vm=require('node:vm'),fs=require('node:fs');let settings={},editor,front,history=[];const ctx={RoofTrim:R,document:{querySelector:()=>null},wallNearestSurface:()=>front};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('public/measure/internal/editor_scripts/roof_trim_editor.js','utf8'),ctx);
 editor=ctx.createRoofTrimEditor({settings:()=>settings,set:v=>settings=v,visible:()=>true,redraw:()=>editor.refresh(roof),screen:()=>null,commit:b=>history.push(b),undo:()=>{settings=history.pop();editor.refresh(roof);}});const panels=editor.refresh(roof),event=shiftKey=>({shiftKey,target:{closest:()=>true}}),key=k=>editor.key({key:k,preventDefault(){},stopImmediatePropagation(){}}),pick=(i,shift=false)=>{front={object:{userData:{roofTrimId:panels[i].id}}};assert.equal(editor.pick(event(shift),{},p=>p),true);};
 pick(0);pick(1,true);key('9');key('.');key('5');assert.ok(R.panels(roof,settings).slice(0,2).every(p=>Math.abs(p.height-9.5*.0254)<1e-9));key('Enter');assert.equal(history.length,1);key('1');key('2');key('Escape');assert.ok(R.panels(roof,settings).slice(0,2).every(p=>Math.abs(p.height-9.5*.0254)<1e-9));key('Delete');assert.equal(R.panels(roof,settings).filter(f=>f.deleted).length,2);assert.equal(history.length,2);editor.key({key:'z',ctrlKey:true,preventDefault(){},stopImmediatePropagation(){}});assert.equal(R.panels(roof,settings).filter(f=>f.deleted).length,0);pick(1,true);assert.equal(editor.selected(panels[1].id),false);
});

test('fascia excludes chimney, sidewall, headwall and unclassified boundaries even with saved trim',()=>{
 for(const type of ['chimney','sidewall','headwall','unknown','ridge','valley']){const changed={...roof,connections:roof.connections.map((c,i)=>i===0?{...c,type}:c)};const previous=R.panels(roof).find(f=>f.a.y===0&&f.b.y===0),settings=R.setHeight({},[previous.id],12);assert.equal(R.panels(changed,settings).length,5);assert.ok(!R.panels(changed,settings).some(f=>f.id===previous.id));}
 assert.deepEqual(R.panels({faces:roof.faces}),[]);
 const hole=[p(2,.5,3.25),p(3,.5,3.25),p(3,1,3.5),p(2,1,3.5)];assert.equal(R.panels({...roof,faces:[{...roof.faces[0],holes:[hole]},roof.faces[1]]}).length,6);
});
test('fascia stops where an eave changes to a headwall on one polygon edge',()=>{
 const mid=p(3,0,3),mixed={...roof,points:[...roof.points,mid],connections:[...roof.connections.slice(1),{startIdx:0,endIdx:6,type:'eave'},{startIdx:6,endIdx:1,type:'headwall'}]};
 const bottom=R.panels(mixed).filter(f=>f.a.y===0&&f.b.y===0);assert.equal(bottom.length,1);assert.deepEqual([bottom[0].a.x,bottom[0].b.x].sort(),[0,3]);
});
