const test=require('node:test'),assert=require('node:assert/strict'),F=require('../public/measure/internal/editor_scripts/wall_features.js'),W=require('../public/measure/internal/editor_scripts/wall_solid_geometry.js');const p=(x,y,z=0)=>({x,y,z});
test('catalog and dimensions use feet and support new definitions',()=>{assert.equal(F.defs.get('garage').sizes[0].w,16);const points=[p(0,0),p(4*F.FT,0),p(4*F.FT,6*F.FT),p(0,6*F.FT)];assert.equal(F.label(points),'4 × 6 ft');F.register({id:'test',name:'Test',sizes:[{w:1,h:1,shape:'rectangle'}]});assert.ok(F.defs.has('test'));});
test('resizing preserves free center, bottom center, edge, and corner anchors',()=>{const points=F.shape({left:1,right:2,bottom:2,top:3}),size={w:4,h:6};for(const anchor of [{},{bottom:true},{right:true},{left:true,bottom:true}]){const b=F.bounds(F.resized(points,size,anchor));assert.ok(Math.abs((b.right-b.left)-4*F.FT)<1e-8);if(anchor.bottom)assert.equal(b.bottom,2);else assert.equal((b.bottom+b.top)/2,2.5);if(anchor.right)assert.equal(b.right,2);else if(anchor.left)assert.equal(b.left,1);else assert.equal((b.left+b.right)/2,1.5);}});
test('nearby floor snaps but elevated placements remain elevated',()=>{const boundary=[F.shape({left:0,right:10,bottom:0,top:5})],size={w:3,h:6+8/12},screen=p=>({x:p.x*100,y:p.y*100});const low=F.place(p(4,size.h*F.FT/2+.05),size,boundary,screen),high=F.place(p(4,size.h*F.FT/2+.5),size,boundary,screen);assert.equal(F.bounds(low).bottom,0);assert.ok(Math.abs(F.bounds(high).bottom-.5)<1e-9);assert.equal(F.anchors(low,boundary).bottom,true);});
test('placement validation rejects crossing concavities and overlapping features',()=>{const outline=[p(0,0),p(4,0),p(4,4),p(3,4),p(3,1),p(1,1),p(1,4),p(0,4)];assert.throws(()=>F.validate(F.shape({left:.5,right:3.5,bottom:.5,top:2}),[outline]));const host=F.shape({left:0,right:5,bottom:0,top:5}),a=F.shape({left:1,right:2,bottom:1,top:2});assert.throws(()=>F.validate(a,[host],[{points:a}]));});
test('upright frame gives true dimensions on a rotated wall and round vents stay planar',()=>{const source=[p(0,0,0),p(3,4,0),p(3,4,3),p(0,0,3)],frame=F.frame(source),points=F.shape({left:0,right:2,bottom:0,top:2},'circle').map(p=>W.fromFrame(frame,p));assert.equal(points.length,48);for(const p of points)assert.ok(Math.abs(p.x*4-p.y*3)<1e-8);assert.ok(Math.abs(F.dimensions(points).width-2/F.FT)<1e-8);});
test('rotated custom feature dimensions and resize axes keep their orientation',()=>{const s=Math.SQRT1_2,points=[p(0,0),p(2*s,2*s),p(-s,5*s),p(-3*s,3*s)],f=F.orientedFrame(points),metadata={axis:f.u},local=points.map(p=>W.inFrame(f,p)),next=F.resized(local,{w:4,h:6}).map(p=>W.fromFrame(f,p)),d=F.dimensions(next,metadata);assert.ok(Math.abs(d.width-4)<1e-8);assert.ok(Math.abs(d.height-6)<1e-8);assert.ok(Math.abs(f.u.x)>0&&Math.abs(f.u.y)>0);});

test('view frame is camera-relative for either winding and oblique upright walls',()=>{
 for(const angle of [0,.4,1.5,2.9])for(const side of [-1,1])for(const reverse of [false,true]){const u={x:Math.cos(angle),y:Math.sin(angle),z:0},points=[p(0,0,0),p(u.x*4,u.y*4,0),p(u.x*4,u.y*4,3),p(0,0,3)];if(reverse)points.reverse();const screen=p=>({x:side*(p.x*u.x+p.y*u.y)*80,y:-p.z*90+(p.x*u.x+p.y*u.y)*20}),f=F.viewFrame(points,screen),a=screen(f.origin),right=screen({x:f.origin.x+f.u.x,y:f.origin.y+f.u.y,z:f.origin.z+f.u.z}),up=screen({x:f.origin.x+f.v.x,y:f.origin.y+f.v.y,z:f.origin.z+f.v.z});assert.ok(right.x>a.x);assert.ok(up.y<a.y);assert.ok(Math.abs(f.u.z)<1e-7);assert.ok(Math.abs(Math.hypot(f.u.x,f.u.y,f.u.z)-1)<1e-7);}
});
