const test=require('node:test'),assert=require('node:assert/strict'),C=require('../public/measure/internal/editor_scripts/wall_closed_soffits.js'),K=require('../public/measure/internal/editor_scripts/exterior_geometry.js'),W=require('../public/measure/internal/editor_scripts/wall_solid_geometry.js'),R=require('../public/measure/internal/editor_scripts/exterior_report_model.js');
function fixture(){const p=(x,y,z)=>({x,y,z}),w={id:'wall',bottom:[p(1,1,0),p(9,1,0)],top:[p(1,1,4.5),p(9,1,4.5)]},face={id:w.id,material:'siding',points:[...w.bottom,w.top[1],w.top[0]],holes:[]},state={closedSoffits:true,sources:[{id:'edge',kind:'perimeter',type:'eave',setback:1,a:p(0,1,4.5),b:p(10,1,4.5),originalA:p(0,0,4),originalB:p(10,0,4)}],wallEdits:{}};state.wallEdits.$surfaces=C.build(state,[w]);return {w,face,state};}
const area=f=>{const fr=W.faceFrame(f);return K.area({points:f.points.map(p=>W.inFrame(fr,p)),holes:(f.holes||[]).map(r=>r.map(p=>W.inFrame(fr,p)))});};
test('closed soffits preserve full structural walls and exclude enclosed area from siding',()=>{const {w,face,state}=fixture(),before=JSON.stringify(w),panels=state.wallEdits.$surfaces;assert.ok(panels[0].points.every(p=>p.z===4));K.validateFace(panels[0]);assert.deepEqual(C.apply([w],state),[w]);const parts=C.presentation(face,state);assert.equal(parts.length,2);assert.equal(parts.filter(f=>f.constructionOnly).reduce((s,f)=>s+area(f),0),4);assert.equal(parts.filter(f=>!f.constructionOnly).reduce((s,f)=>s+area(f),0),32);const report=R.build({faces:parts});assert.ok(Math.abs(report.totals.net-32/.3048**2)<.001);assert.equal(report.construction.length,1);assert.equal(JSON.stringify(w),before);});
test('deletion and global toggling restore siding without changing any wall coordinates',()=>{const {w,face,state}=fixture(),before=JSON.stringify(w);state.closedSoffits=false;assert.deepEqual(C.presentation(face,state),[face]);assert.equal(C.presentation(state.wallEdits.$surfaces[0],state).length,0);state.closedSoffits=true;assert.ok(C.presentation(face,state).some(f=>f.constructionOnly));state.wallEdits.$surfaces[0].deleted=true;assert.deepEqual(C.presentation(face,state),[face]);assert.equal(JSON.stringify(w),before);});
test('partial soffit deletion only restores the newly exposed siding interval',()=>{const {face,state}=fixture();state.wallEdits.$surfaces[0].points.forEach(p=>p.x=Math.min(p.x,5));const parts=C.presentation(face,state);assert.equal(parts.filter(f=>f.constructionOnly).reduce((s,f)=>s+area(f),0),2);assert.equal(parts.filter(f=>!f.constructionOnly).reduce((s,f)=>s+area(f),0),34);});
test('zero setbacks, parapets and skylights do not produce closed soffits',()=>{for(const change of [{setback:0},{type:'parapet'},{type:'skylight'}]){const {w,state}=fixture();Object.assign(state.sources[0],change);assert.equal(C.build(state,[w]).length,0);}});
test('drafted soffits retain classification and roof ownership through save/reload',()=>{const {face,state}=fixture(),M=require('../public/measure/internal/editor_scripts/exterior_model.js'),S=require('../public/measure/internal/editor_scripts/base_sketch_geometry.js'),panel=state.wallEdits.$surfaces[0],frame=W.faceFrame(panel),d={frame,closedSoffit:panel.closedSoffit,roofLayer:true,members:[],faces:[{id:'panel',points:panel.points.map(p=>W.inFrame(frame,p))}]};S.ensure(d);panel.drafted=true;state.wallEdits.$drafts={soffit:d};assert.equal(M.draftFace(d,d.faces[0]).roofLayer,true);assert.ok(C.presentation(face,JSON.parse(JSON.stringify(state))).some(f=>f.constructionOnly));d.deletedFaces=[d.faces[0].points.map(p=>p.nodeId).sort().join('|')];assert.deepEqual(C.presentation(face,state),[face]);});
test('neighboring undersides meet at their common outer roof corner',()=>{const {w,state}=fixture(),p=(x,y,z)=>({x,y,z}),right={id:'right',bottom:[p(9,1,0),p(9,9,0)],top:[p(9,1,4.5),p(9,9,4.5)]};state.sources.push({id:'right',kind:'perimeter',type:'eave',setback:1,a:p(9,0,4.5),b:p(9,10,4.5),originalA:p(10,0,4),originalB:p(10,10,4)});const faces=C.build(state,[w,right]);assert.equal(faces.length,2);for(const f of faces){K.validateFace(f);assert.ok(f.points.some(p=>p.x===10&&p.y===0&&p.z===4));}});
