const test=require('node:test'),assert=require('node:assert/strict');
const T=require('../public/measure/internal/editor_scripts/wall_steps.js'),W=require('../public/measure/internal/editor_scripts/wall_solid_geometry.js');
const p=(x,z,y=0)=>({x,y,z}),wall={id:'upper',points:[p(0,0),p(10,2),p(10,5),p(0,5)]},frame=W.faceFrame(wall),pair=[p(0,0),p(10,2)],near=(a,b)=>Math.abs(a-b)<1e-6;
function check(pattern,n){assert.deepEqual(pattern.points[0],pair[0]);assert.deepEqual(pattern.points.at(-1),pair[1]);const edges=pattern.points.slice(1).map((p,i)=>[pattern.points[i],p]),risers=edges.filter(([a,b])=>near(a.x,b.x)),runs=edges.filter(([a,b])=>near(a.z,b.z));assert.equal(risers.length,n);assert.ok(risers.every(([a,b])=>near(Math.abs(b.z-a.z),2/n)));assert.ok(runs.every(([a,b])=>b.x>=a.x));assert.ok(edges.every(([a,b])=>near(a.x,b.x)||near(a.z,b.z)));return {risers,runs};}
test('equal rises and regular spacing with endpoints fixed, from one step past ten',()=>{for(const n of [1,2,3,10,11,25,100]){const t=T.pattern(pair,frame,n,.431),{risers,runs}=check(t,n);for(let i=1;i<risers.length;i++)assert.ok(near(risers[i][0].x-risers[i-1][0].x,10/(n+1)));for(const [a,b]of runs.slice(1,-1))assert.ok(near(b.x-a.x,10/(n+1)));}});
test('mouse horizontal reference sets riser phase, including near the far endpoint',()=>{for(const reference of [.07,.37,.82,.95]){const t=T.pattern(pair,frame,5,p(reference*10,reference*2)),{risers}=check(t,5);assert.ok(risers.some(([a,b])=>near(a.x,reference*10)));}});
test('phase boundaries, endpoint anchors, reverse edges, and falling grades remain deterministic',()=>{for(const reference of [0,.2,.4,1]){check(T.pattern(pair,frame,5,reference),5);assert.deepEqual(T.pattern(pair,frame,5,reference).points,T.pattern(pair.slice().reverse(),frame,5,reference).points);}const t=T.pattern([p(0,2),p(10,0)],frame,3,.4);assert.ok(t.points.every(p=>p.z>=0&&p.z<=2));assert.equal(t.points[0].z,2);assert.equal(t.points.at(-1).z,0);});
test('steps align with elevation on rotated vertical walls and with axes on flat faces',()=>{const rotated=wall.points.map(q=>({x:q.x*.6,y:q.x*.8,z:q.z})),t=T.pattern(rotated.slice(0,2),W.faceFrame({points:rotated}),4,.5);for(const q of t.points)assert.ok(near(q.x*.8-q.y*.6,0));const flat={points:[{x:0,y:0,z:3},{x:10,y:2,z:3},{x:10,y:5,z:3},{x:0,y:5,z:3}]};const tf=T.pattern(flat.points.slice(0,2),W.faceFrame(flat),4,.3);assert.ok(tf.points.every(q=>q.z===3));});
test('horizontal, vertical, invalid count, and off-plane lines are rejected',()=>{for(const selected of [[p(0,0),p(10,0)],[p(0,0),p(0,2)],[p(0,0),p(10,2,1)]])assert.throws(()=>T.pattern(selected,frame));for(const count of [0,-1,1.5,Infinity])assert.throws(()=>T.pattern(pair,frame,count));});
test('a diagonal shared divider is replaced identically in both incident faces',()=>{const lower={id:'lower',points:[p(0,0),p(0,-2),p(10,-2),p(10,2)]},before=JSON.stringify([wall,lower]),t=T.pattern(pair,frame,4,.4),result=T.apply([wall,lower],t);assert.equal(result.affected.length,2);for(const q of t.points)for(const f of result.faces)assert.ok(f.points.some(p=>near(p.x,q.x)&&near(p.z,q.z)));assert.equal(JSON.stringify([wall,lower]),before);});
test('a selected portion of a longer boundary changes only that portion and retains split points',()=>{const f={id:'partial',points:[p(-2,-.4),p(12,2.4),p(12,5),p(-2,5)],retainedPoints:[{...p(3,.6),sourceSplit:true},p(7,4)]},t=T.pattern(pair,frame,3,.4),result=T.apply([f],t).faces[0];assert.deepEqual(result.points[0],f.points[0]);assert.ok(result.points.some(q=>q.x===12&&q.z===2.4));assert.equal(result.retainedPoints.length,2);assert.equal(result.retainedPoints[0].sourceSplit,true);assert.equal(result.retainedPoints[0].x,3);assert.deepEqual(result.retainedPoints[1],p(7,4));});
test('noncoplanar neighboring faces cannot be torn open by a stair pattern',()=>{const other={id:'other',points:[p(0,0),p(10,2),p(10,2,2),p(0,0,2)]},before=JSON.stringify([wall,other]);assert.throws(()=>T.apply([wall,other],T.pattern(pair,frame,3,.5)),/plane/);assert.equal(JSON.stringify([wall,other]),before);});
test('an offset that crosses the opposite boundary is rejected without changing input',()=>{const thin={id:'thin',points:[p(0,0),p(10,2),p(10,2.1),p(0,.1)]},before=JSON.stringify(thin);assert.throws(()=>T.apply([thin],T.pattern(pair,W.faceFrame(thin),1,.1)));assert.equal(JSON.stringify(thin),before);});
test('touching faces and original vertex metadata do not acquire unrelated changes',()=>{const unrelated={id:'neighbor',points:[{...p(0,0),nodeId:'other-0'},p(-2,0),p(-2,3),p(0,3)]};const result=T.apply([wall,unrelated],T.pattern(pair,frame,3,.4));assert.deepEqual(result.affected,['upper']);assert.equal(result.faces[1],unrelated);});

 test('resizing tread width retains count, endpoints and monotone geometry at either limit',()=>{for(const n of [1,2,5,12])for(const scale of [.05,.7,1,1.4,20])for(const anchor of [0,.37,.95,1]){const t=T.pattern(pair,frame,n,anchor,scale);check(t,n);assert.ok(t.spacing>0);if(n>1)assert.ok((n-1)*t.spacing<10);}});
 test('wheel sizing normalizes delta modes and reverses smoothly',()=>{assert.equal(T.wheelScale(1,{deltaY:3,deltaMode:1}),T.wheelScale(1,{deltaY:48,deltaMode:0}));const up=T.wheelScale(1,{deltaY:-100});assert.ok(up>1);assert.ok(near(T.wheelScale(up,{deltaY:100}),1));});

test('small wheel changes do not switch reference risers or jump at unit scale',()=>{for(const ref of [.4,.5,.6,.8]){const original=T.pattern(pair,frame,4,ref);for(const scale of [.9999,1.0001]){const resized=T.pattern(pair,frame,4,ref,scale);assert.equal(resized.points.length,original.points.length);for(let i=0;i<original.points.length;i++)assert.ok(Math.hypot(resized.points[i].x-original.points[i].x,resized.points[i].z-original.points[i].z)<.002);}}});
test('wheel has fine control and original split points retain their run coordinates throughout resizing',()=>{assert.ok(T.wheelScale(1,{deltaY:-120})<1.013);const original=[2.1,3.7,6.2,8.6].map(x=>({...p(x,x*.2),anchorId:'original-'+x}));for(const scale of [.2,.7,.9999,1,1.0001,1.3]){const t=T.pattern(pair,frame,4,.4,scale),result=T.apply([{...wall,retainedPoints:original}],t).faces[0];for(const anchor of original){const q=result.retainedPoints.find(p=>p.anchorId===anchor.anchorId);assert.ok(q);assert.ok(near(q.x,anchor.x)&&near(q.y,anchor.y));}}});
