const test=require('node:test'),assert=require('node:assert/strict'),C=require('../public/measure/internal/editor_scripts/wall_closed_soffits.js'),K=require('../public/measure/internal/editor_scripts/exterior_geometry.js');
function fixture(){const p=(x,y,z)=>({x,y,z}),w={id:'wall',bottom:[p(1,1,0),p(9,1,0)],top:[p(1,1,4.5),p(9,1,4.5)]},state={sources:[{id:'edge',kind:'perimeter',type:'eave',setback:1,a:p(0,1,4.5),b:p(10,1,4.5),originalA:p(0,0,4),originalB:p(10,0,4)}],wallEdits:{}};return {w,state};}
test('closed soffits lower wall tops to the fascia bottom with horizontal editable roof faces',()=>{const {w,state}=fixture(),before=JSON.stringify(w),panels=C.build(state,[w],[{a:{x:0,y:0,z:4},b:{x:10,y:0,z:4},height:.15}]);assert.equal(panels.length,1);assert.ok(panels[0].roofLayer);assert.ok(panels[0].points.every(p=>p.z===3.85));K.validateFace(panels[0]);state.wallEdits.$surfaces=panels;assert.ok(C.apply([w],state)[0].top.every(p=>p.z===3.85));assert.equal(JSON.stringify(w),before);panels[0].deleted=true;assert.deepEqual(C.apply([w],state),[w]);});
test('zero setbacks, parapets and skylights do not produce closed soffits',()=>{for(const change of [{setback:0},{type:'parapet'},{type:'skylight'}]){const {w,state}=fixture();Object.assign(state.sources[0],change);assert.equal(C.build(state,[w]).length,0);}});
test('partial removal restores only the wall interval without a soffit',()=>{const {w,state}=fixture(),panels=C.build(state,[w]);panels[0].points=panels[0].points.map(p=>({...p,x:Math.min(p.x,5)}));state.wallEdits.$surfaces=panels;const parts=C.apply([w],state);assert.equal(parts.length,2);assert.ok(parts[0].top.every(p=>p.z===4));assert.ok(parts[1].top.every(p=>p.z===4.5));assert.equal(parts[0].top[1].x,5);});
test('drafted soffits retain roof ownership and wall binding through drawing and reload',()=>{const {w,state}=fixture(),M=require('../public/measure/internal/editor_scripts/exterior_model.js'),W=require('../public/measure/internal/editor_scripts/wall_solid_geometry.js'),S=require('../public/measure/internal/editor_scripts/base_sketch_geometry.js'),face=C.build(state,[w])[0],frame=W.faceFrame(face),d={frame,closedSoffit:face.closedSoffit,roofLayer:true,members:[],faces:[{id:'panel',points:face.points.map(p=>W.inFrame(frame,p))}]};S.ensure(d);state.wallEdits.$surfaces=[{...face,drafted:true}];state.wallEdits.$drafts={soffit:d};assert.equal(M.draftFace(d,d.faces[0]).roofLayer,true);assert.ok(C.apply([w],JSON.parse(JSON.stringify(state)))[0].top.every(p=>p.z===4));d.deletedFaces=[d.faces[0].points.map(p=>p.nodeId).sort().join('|')];assert.deepEqual(C.apply([w],state),[w]);});

test('neighboring undersides meet at their common outer roof corner',()=>{
 const {w,state}=fixture(),p=(x,y,z)=>({x,y,z}),right={id:'right',bottom:[p(9,1,0),p(9,9,0)],top:[p(9,1,4.5),p(9,9,4.5)]};state.sources.push({id:'right',kind:'perimeter',type:'eave',setback:1,a:p(9,0,4.5),b:p(9,10,4.5),originalA:p(10,0,4),originalB:p(10,10,4)});const faces=C.build(state,[w,right]);assert.equal(faces.length,2);for(const f of faces){K.validateFace(f);assert.ok(f.points.some(p=>p.x===10&&p.y===0&&p.z===4));}state.wallEdits.$surfaces=faces;assert.deepEqual(C.apply([w,right],state).map(w=>w.id),['wall','right']);
});
