/** Inventory of application ownership, not a claim that every legacy endpoint is
 * a published operation. Adding an app requires an explicit publication decision. */
export const applicationPublication = {
  partners:{providers:["collaboration"],domains:["collaboration"],note:"Authenticated organization connections, resource sharing and partner exchanges. Dedicated invitations and privacy administration remain explicit authenticated APIs."},
  assistant: { providers: [], domains: [], note: "Consumes the shared authorized publication catalog; assistant conversations, instructions and personal memories retain their dedicated subject-scoped APIs." },
  projects: { providers: ["projects", "custom-fields-project"], domains: ["projects", "custom-fields"] },
  contacts: { providers: ["customers", "custom-fields-contact", "contacts"], domains: ["projects", "custom-fields", "contacts"] },
  photos: { providers: ["media"], domains: ["media", "channels"], note:"Feed posts use hidden Channels roots; published feed reads, comments and reactions reauthorize source artifacts and default-on view/participation permissions." },
  receipts: { providers: ["media"], domains: ["media"] },
  proposals: { providers: ["proposals"], domains: ["proposals"] },
  docs: { providers: ["documents"], domains: ["documents"] },
  documents: { providers: ["documents", "document-modules"], domains: ["documents"] },
  "web-editor": { providers: ["websites"], domains: ["websites"] },
  materials: { providers: ["materials", "materials-calculus", "materials-inputs", "project-widgets"], domains: ["materials"] },
  money: { providers: ["payments"], domains: ["payments"] },
  "project-request": { providers: ["projects"], domains: ["projects"] },
  "firstmeasure/order": { providers: ["firstmeasure"], domains: ["firstmeasure"] },
  "project-map": { providers: ["projects"], domains: ["projects"] },
  "customer-portal": { providers: ["customer-portal"], domains: ["customerPortal"] },
  "project-schedule": { providers: ["calendar"], domains: ["scheduling", "workforce"] },
  comms: { providers: ["comms", "customer-calls"], domains: ["comms"], note: "Call records, retained transcripts and recording metadata enforce branch and department authority, including frozen replay." },
  measurements: { providers: ["datasets", "firstmeasure", "project-widgets"], domains: ["datasets"] },
  checklists: { providers: ["work", "todos"], domains: ["work"] },
  scheduling: { providers: ["workforce-departments", "calendar"], domains: ["scheduling", "workforce"] },
  training: { providers: ["training"], domains: ["training"] },
  "training-studio": { providers: ["training"], domains: ["training"] },
  equipment: { providers: ["equipment"], domains: ["equipment"] },
  invoices: { providers: ["payments"], domains: ["payments"] },
  financials: { providers: ["financials"], domains: ["payments"] },
  stats: { providers: ["stats"], domains: ["stats"], note: "Saved views, schema and queries are read-only; warehouse refresh is an explicit action." },
  payroll: { providers: ["payroll"], domains: ["payroll"], note: "Typed payroll ledger, schedules, policies, earnings, runs, timesheets, contractors and artifacts; subject-scoped self earnings; shared native view widgets and explicit domain mutations. Reads never reconcile scope commissions. Downloads retain authenticated binary HTTP delivery." },
  chat: { providers: ["chat"], domains: ["chat"] },
  channels: { providers: ["channels"], domains: ["channels"], note:"Project trays reuse Channels records and its subject authorization; note creation, sharing, pinning, editing, deletion and restoration are published operations. The feature flag changes rendering, not storage." },
  canvassing: { providers: ["canvassing"], domains: ["canvassing"] },
  feedback: { providers: ["feedback"], domains: ["feedback"] },
  settings: { providers: ["workforce-departments", "notification-rules", "organization", "scopes", "custom-fields-organization", "forms", "lead-import"], domains: ["custom-fields", "workforce", "leads"], note: "Settings owns external connections with dynamic external.<connectionId> providers and versioned connection actions, loaded per organization. Settings are selectively published; credentials and platform administration are never generic data exports. Platform Billing owns dedicated authenticated catalog, subscription and invoice flows under /v1/platform-billing; commercial changes are not exposed to tenant modules or agent tools." },
  crew: { providers: ["work", "todos", "workforce"], domains: ["work", "workforce"] },
  sales: { providers: ["work", "todos", "workforce"], domains: ["work", "workforce"] },
  field_visit: { providers: ["work"], domains: ["work"] },
  signatures: { providers: ["documents"], domains: ["documents"] },
  billing: { providers: ["billing", "payments"], domains: ["payments"], note: "Credit balance and project billing publications; organization subscription checkout retains its dedicated authenticated flow." },
  help: { providers: [], domains: [], note: "Presentation shell; owns no project data or business actions." },
  onboarding: { providers: ["organization"], domains: [], note: "Uses organization profile; account and credential setup retains its dedicated flow." },
  "promo-inject": { providers: [], domains: [], note: "Presentation injection; owns no project data or business actions." },
  referrals: { providers: ["referrals", "customers"], domains: ["referrals"], note: "Eligibility and explicit referral initialization action; referral setup is not a side effect of a data read." },
  pricebook: { providers: ["pricebook"], domains: ["pricebook"] },
  tutorial: { providers: [], domains: [], note: "Presentation shell; owns no project data or business actions." }
} as const;
