/** Inventory of application ownership, not a claim that every legacy endpoint is
 * a published operation. Adding an app requires an explicit publication decision. */
export const applicationPublication = {
  projects: { providers: ["projects"], domains: ["projects"] },
  contacts: { providers: ["customers"], domains: ["projects"] },
  photos: { providers: ["media"], domains: ["media"] },
  receipts: { providers: ["media"], domains: ["media"] },
  proposals: { providers: ["proposals"], domains: ["proposals"] },
  docs: { providers: ["documents"], domains: ["documents"] },
  documents: { providers: ["documents", "document-modules"], domains: ["documents"] },
  "web-editor": { providers: ["websites"], domains: ["websites"] },
  materials: { providers: ["materials"], domains: ["materials"] },
  money: { providers: ["payments"], domains: ["payments"] },
  "project-request": { providers: ["projects"], domains: ["projects"] },
  "firstmeasure/order": { providers: ["firstmeasure"], domains: ["firstmeasure"] },
  "project-map": { providers: ["projects"], domains: ["projects"] },
  "customer-portal": { providers: ["customer-portal"], domains: ["customerPortal"] },
  "project-schedule": { providers: ["calendar"], domains: ["scheduling"] },
  comms: { providers: ["comms"], domains: ["comms"] },
  measurements: { providers: ["datasets", "firstmeasure"], domains: ["datasets"] },
  checklists: { providers: ["work"], domains: ["work"] },
  scheduling: { providers: ["calendar"], domains: ["scheduling"] },
  training: { providers: ["training"], domains: ["training"] },
  "training-studio": { providers: ["training"], domains: ["training"] },
  equipment: { providers: ["equipment"], domains: ["equipment"] },
  invoices: { providers: ["payments"], domains: ["payments"] },
  financials: { providers: ["financials"], domains: ["payments"] },
  stats: { providers: ["stats"], domains: ["stats"], note: "Saved views, schema and queries are read-only; warehouse refresh is an explicit action." },
  payroll: { providers: ["payroll"], domains: ["payroll"] },
  chat: { providers: ["chat"], domains: ["chat"] },
  channels: { providers: ["channels"], domains: ["channels"] },
  canvassing: { providers: ["canvassing"], domains: ["canvassing"] },
  feedback: { providers: ["feedback"], domains: ["feedback"] },
  settings: { providers: ["organization", "scopes"], domains: [], note: "Settings are selectively published; credentials and platform administration are never generic data exports. Platform Billing owns dedicated authenticated catalog, subscription and invoice flows under /v1/platform-billing; commercial changes are not exposed to tenant modules or agent tools." },
  crew: { providers: ["work", "workforce"], domains: ["work", "workforce"] },
  sales: { providers: ["work", "workforce"], domains: ["work", "workforce"] },
  field_visit: { providers: ["work"], domains: ["work"] },
  signatures: { providers: ["documents"], domains: ["documents"] },
  billing: { providers: ["billing", "payments"], domains: ["payments"], note: "Credit balance and project billing publications; organization subscription checkout retains its dedicated authenticated flow." },
  help: { providers: [], domains: [], note: "Presentation shell; owns no project data or business actions." },
  onboarding: { providers: ["organization"], domains: [], note: "Uses organization profile; account and credential setup retains its dedicated flow." },
  "promo-inject": { providers: [], domains: [], note: "Presentation injection; owns no project data or business actions." },
  referrals: { providers: ["referrals", "customers"], domains: ["referrals"], note: "Eligibility and explicit referral initialization action; referral setup is not a side effect of a data read." },
  pricebook: { providers: ["pricebook"], domains: ["pricebook"] },
  tutorial: { providers: [], domains: [], note: "Presentation shell; owns no project data or business actions." }
} as const;
