import { registerDataProvider } from "./providers.js";
import type { AccessPolicy, PublicationContext, SourceRef, JsonSchema } from "./contracts.js";
import { readDocument, readBranchModule } from "../storage.js";
import { forbidden, badRequest } from "../errors.js";
import { contentHash } from "./validation.js";
type Obj=Record<string,unknown>;
function object(v:unknown):Obj{return v&&typeof v==="object"&&!Array.isArray(v)?v as Obj:{};}
function projectAccess(permissions=["view_projects"]):AccessPolicy{return {scopes:["project"],permissions,systemKinds:["work","module","agent"],authorize:async(ctx,t)=>{await readDocument(ctx.organizationId,"projects",t.projectId!);}};}
function orgAccess(permissions=["view_projects"]):AccessPolicy{return {scopes:["organization"],permissions,systemKinds:["work","module","agent"]};}
function registerRows(id:string,apps:string[],fields:string[],access:AccessPolicy,load:(ctx:PublicationContext,ref:SourceRef)=>Promise<unknown[]>,subjectKey?:string){
 const schema:JsonSchema={type:"object",properties:Object.fromEntries(fields.map(f=>[f,{type:["string","number","boolean","null"]}])),additionalProperties:false};
 const rows=async(ctx:PublicationContext,ref:SourceRef)=>(await load(ctx,ref)).map(row=>{const r=object(row);return Object.fromEntries(fields.filter(f=>r[f]===null||["string","number","boolean"].includes(typeof r[f])).map(f=>[f,r[f]]));});
 registerDataProvider({id,version:"1",apps,exports:{records:{description:`Published ${id} records, filtered to the permitted subject.`,schema:{type:"array",items:schema},schemaVersion:"1",access,...(subjectKey?{authorizeSnapshot:async(ctx:PublicationContext,ref:SourceRef,result:{provenance:Record<string,unknown>})=>{if(result.provenance.viewerUserId!==ctx.auth?.userId)throw forbidden("snapshot_viewer_denied","This snapshot contains another user's view.");const captured=result.provenance.subjectIds;if(!Array.isArray(captured)||captured.some(id=>typeof id!=="string"))throw forbidden("snapshot_subjects_missing","Snapshot subject authorization metadata is unavailable.");const allowed=new Set((await rows(ctx,ref)).map(row=>String(row[subjectKey])));if(captured.some(id=>!allowed.has(id)))throw forbidden("snapshot_subject_denied","A captured subject is no longer accessible.");}}:{}),read:async(ctx,ref)=>{const value=await rows(ctx,ref);return {value,...(subjectKey?{provenance:{viewerUserId:ctx.auth!.userId,subjectIds:value.map(row=>String(row[subjectKey]))}}:{})};},list:async(ctx,ref,page)=>{const all=await rows(ctx,ref);all.sort((a,b)=>String(a.id).localeCompare(String(b.id)));const signature=contentHash({ref,all,user:ctx.auth?.userId||"system"});let offset=0;if(page.cursor){try{const c=JSON.parse(Buffer.from(page.cursor,"base64url").toString());if(c.signature!==signature||!Number.isInteger(c.offset)||c.offset<0)throw Error();offset=c.offset;}catch{throw badRequest("source_cursor_invalid","The source list changed or its cursor is invalid.");}}const items=all.slice(offset,offset+page.limit);return {items,...(offset+items.length<all.length?{nextCursor:Buffer.from(JSON.stringify({signature,offset:offset+items.length})).toString("base64url")}: {})};}}}});
}
let registered=false;
export function registerDomainDataProviders(){if(registered)return;registered=true;
 registerRows("payments",["money","invoices","billing"],["id","label","amount_cents","allocated_cents","balance_due_cents","due_at","status"],projectAccess(),async(ctx,ref)=>(await import("../../payments/storage.js")).listProjectObligations(ctx.organizationId,ref.target.projectId!));
 const moneyFields=["project_total_cents","total_collected_cents","total_remaining_cents","projected_revenue_cents","revenue_to_date_cents","projected_expenses_cents","expenses_to_date_cents","projected_profit_cents","profit_to_date_cents"];
 registerRows("financials",["financials"],moneyFields,projectAccess(["manage_projects|manage_billing"]),async(ctx,ref)=>[(await (await import("../../payments/storage.js")).projectMoneySummary(ctx.organizationId,ref.target.projectId!))]);
 registerRows("equipment",["equipment"],["id","name","label","status","type_id","category_id","yard_id","serial_number"],{...orgAccess(["equipment.view|equipment.manage|equipment.service|manage_company_settings"]),applications:["management","field"],capabilities:["apps.equipment"]},async(ctx)=>(await import("../../equipment/storage.js")).listUnits(ctx.organizationId));
 registerRows("payroll",["payroll"],["id","project_id","payee_id","payee_type","earning_kind","amount_cents","status","created_at"],{...projectAccess(["manage_payroll|manage_company_settings"]),capabilities:["apps.payroll"]},async(ctx,ref)=>(await import("../../payroll/storage.js")).listPayrollLedgerEntries(ctx.organizationId,{project_id:ref.target.projectId}));
 registerRows("scopes",["settings"],["id","name","version","enabled","description"],{...orgAccess(["manage_company_settings"])},async(ctx,ref)=>(await import("../../scopes/storage.js")).listScopeTemplates(ctx.organizationId,ref.target.branchId||ctx.branchId||"default"));
 registerRows("work",["checklists","crew","sales","field_visit"],["id","plan_id","project_id","title","name","status","kind","due_at","completed_at"],projectAccess(),async(ctx,ref)=>(await import("../../work/storage.js")).listNodeRecords(ctx.organizationId,{project_id:ref.target.projectId}));
 registerRows("workforce",["crew","sales"],["id","name","display_name","status","email"],orgAccess(["manage_company_users|manage_company_user_permissions|manage_company_settings"]),async(ctx)=>(await import("../../workforce/service.js")).listWorkforceUsers(ctx.organizationId));
 registerRows("stats",["stats"],["id","name","description","created_at","updated_at"],orgAccess(["view_projects|manage_projects|manage_company_settings"]),async(ctx)=>{const value=await (await import("../../stats/service.js")).listStatsViews(ctx.organizationId);return Array.isArray(value)?value:[];});
 registerRows("channels",["channels"],["id","name","type","archived_at","created_at"],{scopes:["organization"],permissions:[],applications:["management","field"],capabilities:["apps.channels"],authorize:ctx=>{if(!ctx.auth)throw forbidden("source_user_required","Channel publication requires an authenticated member.");}},async(ctx)=>{const value=await (await import("../../channels/service.js")).listChannelsForUser(ctx.auth!,{initialize:false});return Array.isArray(value)?value:[];},"id");
 registerRows("training",["training","training-studio"],["id","name","title","status","description"],{scopes:["organization"],applications:["management","field"],permissions:[],capabilities:["apps.training"],authorize:ctx=>{if(!ctx.auth)throw forbidden("source_user_required","Training publication requires an authenticated learner.");}},async(ctx)=>{const roles=[...(ctx.auth!.accessProfile?.access_role_ids||[]),ctx.auth!.role].filter((r):r is string=>typeof r==="string");const value=await (await import("../../training/service.js")).listMyCourses(ctx.organizationId,{userId:ctx.auth!.userId,roleIds:roles},{initialize:false});return Array.isArray(value)?value:[];},"id");
 registerRows("canvassing",["canvassing"],["id","lat","lng","address","status_id","project_id","created_at","updated_at"],{...orgAccess([]),capabilities:["canvassing.app"],authorize:async(ctx,t)=>{const settings=await readBranchModule(ctx.organizationId,t.branchId||ctx.branchId||"default","canvassing").catch(()=>null);if(object(settings?.data).enabled===false)throw forbidden("canvassing_disabled","Canvassing is disabled for this branch.");}},async(ctx,ref)=>(await import("../../canvassing/service.js")).listPins(ctx.organizationId,ref.target.branchId||ctx.branchId||"default"));
 registerRows("comms",["comms"],["id","channel","direction","subject","text_body","text","created_at","status"],{...projectAccess(["view_comms|view_projects|manage_projects|manage_company_settings"]),capabilities:["apps.comms"],systemKinds:[],authorize:async(ctx,t)=>{if(!ctx.auth)throw forbidden("source_user_required","Communications require an authenticated project viewer.");await (await import("../../comms/calls/service.js")).projectContext(ctx.auth,t.projectId!);}},async(ctx,ref)=>(await import("../../comms/service.js")).projectCommsFeed(ctx.organizationId,ref.target.projectId!,{limit:500}));
 registerRows("chat",["chat"],["conversation_id","subject","visitor_name","unread_count","last_message_at","conversation_status"],{...orgAccess(["view_live_chat"]),systemKinds:[],capabilities:["apps.live_chat"],authorize:ctx=>{if(!ctx.auth)throw forbidden("source_user_required","Chat publication requires an authenticated inbox viewer.");}},async(ctx)=>(await import("../../chat/storage.js")).listInboxConversations(ctx.organizationId,ctx.auth!.userId,{limit:200,status:"all"}),"conversation_id");
}
