<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Experimental Admin</title><link rel="icon" type="image/png" href="/images/icon.png"><link rel="apple-touch-icon" href="/images/icon.png"><link rel="stylesheet" href="/fonts.css">
<style>body{margin:0;background:#f0f2f5;color:#202124;font-family:Montserrat,Arial,sans-serif;display:grid;min-height:100vh;place-items:center}main{box-sizing:border-box;width:min(440px,92vw);padding:32px;background:white;border:1px solid #dadce0;border-radius:16px}img{width:130px}h1{font-size:24px}p{line-height:1.6;color:#5f6368}label{display:block;margin-top:18px}input,button{box-sizing:border-box;width:100%;padding:12px;margin-top:8px;border:1px solid #dadce0;border-radius:8px;font:inherit}button{background:#d93025;color:white;cursor:pointer;margin-top:24px}#error{color:#b0261e}a{color:#b0261e}</style></head>
<body><main><img src="/images/logo_red.png" alt="FirstMate" onerror="this.hidden=true"><h1>Experimental Admin</h1><p>Sign in with an authorized administrator account to create companies, choose feature workflows, and open their sessions.</p>
<form id="login"><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button>Sign in</button><p id="error" role="alert"></p></form><p><a href="/portal/login.php">Back to company login</a></p></main>
<script>
const form=document.getElementById('login');
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;document.getElementById('error').textContent='';try{const response=await fetch('/v1/signup-sandbox/admin/login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Unable to sign in.');location.replace('/portal/signup-sandbox/');}catch(error){document.getElementById('error').textContent=error.message;}finally{button.disabled=false;}});
</script></body></html>
