import { readDocument } from '../storage.js';
import { hasResourcePermission, matchesDepartmentFilter } from '../auth.js';
import { registerDataProvider } from '../publication/providers.js';
import { badRequest, forbidden } from '../errors.js';
import type { AccessPolicy, PublicationContext, TargetRef } from '../publication/contracts.js';
const fields=['id','name','title','first_name','last_name','email','phone','address','city','state','status','stage','document_type','type','created_at','updated_at','total_cents'];
const schema={type:'object',properties:Object.fromEntries(fields.map(k=>[k,{type:['string','number','boolean','null']}])),additionalProperties:false};
const pick=(data:any,id:string)=>({...Object.fromEntries(fields.filter(k=>data[k]===null||['string','number','boolean'].includes(typeof data[k])).map(k=>[k,data[k]])),id});
async function project(ctx:PublicationContext,t:TargetRef){const row=await readDocument(ctx.organizationId,'projects',t.projectId!);if(ctx.auth&&(!hasResourcePermission(ctx.auth,'view_projects',row.data)||!matchesDepartmentFilter(ctx.auth,row.data)))throw forbidden('widget_project_denied','Project is unavailable.');return row;}
let registered=false;
export function registerObjectWidgets(){
 if(registered)return;registered=true;
 const access:AccessPolicy={scopes:['project'],permissions:['view_projects'],scopedPermissions:true,authorize:async(ctx,t)=>{await project(ctx,t);}};
 registerDataProvider({id:'widget-objects',version:'1',apps:['projects','contacts','documents'],exports:{
  'secure-entry':{description:'Secure credential form availability. Values are never published.',schema:{type:'object',properties:{available:{const:true}},required:['available'],additionalProperties:false},schemaVersion:'1',access:{scopes:['organization'],permissions:['manage_company_settings'],applications:false,capabilities:['platform.connections']},read:async()=>({value:{available:true}})},
  assignments:{description:'Eligible assignment references from the workforce domain, without private member settings.',schema:{type:'object',additionalProperties:true},schemaVersion:'1',access:{scopes:['organization','project'],permissions:['view_projects']},read:async(ctx,ref)=>{const result=await (await import('../../workforce/service.js')).resolveAssignableSubjects(ctx.organizationId,ref.target.branchId||ctx.branchId||'default',{});return {value:{subjects:(result.subjects as any[]).map(row=>({id:row.id,name:row.name,subject_type:row.subject_type,resource_id:row.resource_id,resource_kind:row.resource_kind}))}};}},
  project:{description:'Authorized project summary fields.',schema,schemaVersion:'1',access,read:async(ctx,ref)=>{if(ref.target.id&&ref.target.id!==ref.target.projectId)throw forbidden('widget_project_mismatch','Project identity mismatch.');const row=await project(ctx,ref.target);return {value:pick(row.data,row.id),revision:String(row.revision)};}},
  contact:{description:'Summary of a saved contact in its owning project.',schema,schemaVersion:'1',access:{...access,permissions:['view_contacts'],authorize:async(ctx,t)=>{await readDocument(ctx.organizationId,'projects',t.projectId!);}},read:async(ctx,ref)=>{const {resolveContact}=await import('../../contacts/service.js');const r=await resolveContact(ctx.organizationId,{project_id:ref.target.projectId,contact_id:ref.target.id});return {value:pick(r.contact,String(ref.target.id)),revision:String(r.parent.revision)};}},
  user:{description:'Organization member summary without role grants, credentials or private settings.',schema,schemaVersion:'1',access:{scopes:['organization'],permissions:['manage_company_users']},read:async(ctx,ref)=>{if(!ref.target.id)throw badRequest('widget_id_required','Choose a user.');const r=await readDocument(ctx.organizationId,'users',ref.target.id);return {value:pick(r.data,r.id),revision:String(r.revision)};}},
  document:{description:'Authorized document identity and summary fields; no private parameters or signing artifacts.',schema,schemaVersion:'1',access,read:async(ctx,ref)=>{const s=await import('../../documents/service.js');const r=await s.readDocumentInstance(ctx.organizationId,String(ref.target.id||''));if(r.project_id!==ref.target.projectId)throw forbidden('widget_document_mismatch','Document belongs to another project.');if(ctx.auth){s.requireDocumentDepartmentAccess(ctx.auth,r,'view_projects');if(!matchesDepartmentFilter(ctx.auth,r))throw forbidden('widget_document_department','Document is outside your department filter.');}return {value:pick(r,String(r.id)),revision:String(r.revision||r.updated_at||'1')};}},
  'document-directory':{description:'Project documents eligible for selection, with department authorization on each result.',schema:{type:'object',properties:{items:{type:'array',items:schema}},required:['items'],additionalProperties:false},schemaVersion:'1',access,read:async(ctx,ref)=>{const s=await import('../../documents/service.js');const rows=await s.listProjectDocuments(ctx.organizationId,ref.target.projectId!);return {value:{items:rows.filter(row=>{try{if(ctx.auth){s.requireDocumentDepartmentAccess(ctx.auth,row,'view_projects');if(!matchesDepartmentFilter(ctx.auth,row))return false;}return true;}catch{return false;}}).map(row=>pick(row,String(row.id)))}};}}
 }});
}
