import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
test('development fixtures enforce isolation, independent toggles and additive retries',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'dev-tools-'));
 Object.assign(process.env,Object.fromEntries(['PLATFORM','PRICEBOOK','SIGNUP_SANDBOX','MESSAGING','CHANNELS','CALLS'].map(key=>[key+'_STORAGE_ROOT',path.join(root,key.toLowerCase())])));
 Object.assign(process.env,{FIRSTMATE_ENV:'test',NODE_ENV:'test',FIRSTMEASURE_DATA_ENVIRONMENT:'development',PLATFORM_HEARTBEAT_DISABLED:'1',EMAIL_OUTBOUND_DISABLED:'1',PLATFORM_SESSION_SECRET:'development-tools-test-secret'});
 const signup=await import('../signup-sandbox/service.js');await signup.ensureSeedData();
 const {authContext:ctx}=await signup.createTestInstance('swf_instant_full_org');
 const tools=await import('../development/synthetic-data.js');
 const storage=await import('../platform/storage.js');
 const only=(...keys:string[])=>({company:'roofing',categories:Object.fromEntries(tools.CATEGORIES.map(c=>[c.id,keys.includes(c.id)]))});
 await assert.rejects(tools.generateSyntheticData(ctx,{company:'plumbing',categories:{}}),/supported/);
 await assert.rejects(tools.generateSyntheticData(ctx,only()),/at least one/);
 await assert.rejects(tools.requireDevelopmentOrganization({...ctx,permissions:{manage_company_settings:false}}),/access/);
 const {default:Fastify}=await import('fastify');const app=Fastify();
 const {registerSignupSandboxApi}=await import('../signup-sandbox/api.js');await app.register(registerSignupSandboxApi,{prefix:'/v1/signup-sandbox'});
 const {setPlatformAuthCookies}=await import('../platform/auth.js');let cookies:string[]=[];
 setPlatformAuthCookies({headers:{host:'localhost'},protocol:'http',socket:{encrypted:false}} as any,{header:(_name:string,value:string[])=>{cookies=value;}} as any,ctx.sessionId,ctx.csrfToken);
 const cookie=cookies.map(c=>c.split(';')[0]).join('; ');
 assert.equal((await app.inject({method:'GET',url:'/v1/signup-sandbox/development'})).statusCode,401);
 assert.equal((await app.inject({method:'GET',url:'/v1/signup-sandbox/development',headers:{cookie}})).statusCode,200);
 assert.equal((await app.inject({method:'POST',url:'/v1/signup-sandbox/development/synthetic-data',headers:{cookie},payload:only('events')})).statusCode,403);
 await app.close();
 const real=await storage.createOrganization({name:'Not a sandbox'});
 await assert.rejects(tools.requireDevelopmentOrganization({...ctx,orgId:String(real.id)}),/sandbox/);
 let result=await tools.generateSyntheticData(ctx,only('projects','equipment','channels'));
 assert.ok(Object.values(result.results).every((r:any)=>r.status==='complete'),JSON.stringify(result.results));
 const ps=await storage.listDocuments(ctx.orgId,'projects');assert.equal(ps.length,4);
 assert.ok(ps.every(p=>(p.data as any).events.length===0));
 assert.equal((await storage.listDocuments(ctx.orgId,'calendar_events')).length,0);
 assert.equal((await storage.listDocuments(ctx.orgId,'project_datasets')).length,4);
 const channels=await import('../channels/storage.js');
 assert.equal((await channels.listChannelRecords(ctx.orgId)).reduce((n,c)=>n+c.message_seq,0),0);
 await storage.upsertDocument(ctx.orgId,'projects',{id:ps[0]!.id,data:{title:'Edited roof'}});
 result=await tools.generateSyntheticData(ctx,{company:'roofing',categories:{}});
 assert.ok(Object.values(result.results).every((r:any)=>r.status==='complete'),JSON.stringify(result.results));
 assert.equal((await storage.listDocuments(ctx.orgId,'calendar_events')).length,6);
 assert.equal((await storage.listDocuments(ctx.orgId,'material_lists')).length,4);
 assert.equal((await storage.listDocuments(ctx.orgId,'documents')).length,4);
 const comm=await import('../messaging/communications_storage.js');
 assert.equal((await comm.listMessageRecords(ctx.orgId)).length,3);
 assert.equal((await (await import('../comms/service.js')).orgCommsInbox(ctx.orgId,{channel:'email'})).length,3);
 assert.ok((await comm.listMessageRecords(ctx.orgId)).every(m=>m.direction==='inbound'&&m.status==='received'));
 result=await tools.generateSyntheticData(ctx,{company:'roofing',categories:{}});
 assert.ok(Object.values(result.results).every((r:any)=>r.status==='complete'),JSON.stringify(result.results));
 assert.equal((await storage.listDocuments(ctx.orgId,'material_lists')).length,4);
 assert.equal((await storage.listDocuments(ctx.orgId,'documents')).length,4);
 assert.equal((await storage.readDocument(ctx.orgId,'projects',String(ps[0]!.id))).data?.title,'Edited roof');
 assert.equal((await comm.listMessageRecords(ctx.orgId)).length,3);
 assert.equal((await (await import('../comms/service.js')).orgCommsInbox(ctx.orgId,{channel:'email'})).length,3);
 const concurrent=await Promise.allSettled([tools.generateSyntheticData(ctx,only('events')),tools.generateSyntheticData(ctx,only('events'))]);
 assert.ok(concurrent.some(r=>r.status==='fulfilled'));assert.equal((await storage.listDocuments(ctx.orgId,'calendar_events')).length,6);
 const request_id=crypto.randomUUID();
 const batch=await tools.generateSyntheticData(ctx,{...only('events'),amount:3,request_id});
 assert.equal((batch.results.events as any).created,18);
 assert.equal((await tools.generateSyntheticData(ctx,{...only('events'),amount:3,request_id})).results.events.created,0);
 assert.equal((await tools.generateSyntheticData(ctx,{...only('events'),amount:1,request_id:crypto.randomUUID()})).results.events.created,6);
 await assert.rejects(tools.generateSyntheticData(ctx,{...only('events'),amount:11}),/supported/);
 const scaled=await tools.generateSyntheticData(ctx,{company:'roofing',categories:{},amount:2,request_id:crypto.randomUUID()});
 assert.ok(Object.values(scaled.results).every((r:any)=>r.status==='complete'),JSON.stringify(scaled));
 assert.equal(scaled.results.projects.created,8);assert.equal(scaled.results.material_lists.created,8);assert.equal(scaled.results.document_types.drafts,8);assert.equal(scaled.results.channels.created,8);
 const {env}=await import('../src/config/env.js');const original=env.dataEnvironment;(env as any).dataEnvironment='production';
 await assert.rejects(tools.requireDevelopmentOrganization(ctx),/Not found/);(env as any).dataEnvironment=original;
 console.log(JSON.stringify({ok:true,categories:8,independent:true,repeatSafe:true}));
});
