import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createHash, randomBytes } from "node:crypto";

test("mobile configuration and private builds preserve tenant and deployment boundaries", async () => {
  const root=await mkdtemp(path.join(os.tmpdir(),"mobile-api-"));
  Object.assign(process.env,{NODE_ENV:"test",FIRSTMATE_ENV:"test",FIRSTMEASURE_DATA_ENVIRONMENT:"development",FIRSTMEASURE_DATABASE_MODE:process.env.TEST_POSTGRES_URL?"postgres":"sqlite",DATABASE_URL:process.env.TEST_POSTGRES_URL||"",PLATFORM_HEARTBEAT_DISABLED:"1",FIRSTMEASURE_JOB_WORKERS:"0",EMAIL_OUTBOUND_DISABLED:"1",V1_LOG_LEVEL:"error",FIRSTMEASURE_INDEX_DB_PATH:path.join(root,"index.sqlite"),MOBILE_DEVELOPER_DOWNLOADS_ENABLED:"1"});
  for(const name of ["PLATFORM","FIRSTMEASURE","MESSAGING","CHANNELS","CALLS","INTERNAL","PRICEBOOK"])process.env[`${name}_STORAGE_ROOT`]=path.join(root,name.toLowerCase());
  const {buildApp}=await import("../src/app.js");const platform=await import("../platform/storage.js");
  const {storeLink,developmentDownloadsAllowed}=await import("../mobile/config.js");
  assert.equal(storeLink("https://play.google.com.evil.test/","android"),null);
  assert.equal(storeLink("http://apps.apple.com/test","ios"),null);
  assert.equal(storeLink("https://user@play.google.com/test","android"),null);
  assert.equal(storeLink("https://testflight.apple.com/join/test","testflight"),"https://testflight.apple.com/join/test");
  const app=await buildApp();
  try {
    const registration=await app.inject({method:"POST",url:"/v1/platform/auth/register",payload:{phone:"+12025550882",email:"mobile@example.test",password:"mobile-test-password",name:"Mobile Test",company:"Mobile Company"}});
    assert.equal(registration.statusCode,201,registration.body);
    const org=registration.json().organization.id;
    const set=registration.headers["set-cookie"]!;
    const cookie=(Array.isArray(set)?set:[set]).map(v=>v.split(";")[0]).join("; ");
    const config=`/v1/mobile/organizations/${org}/config`, apk=`/v1/mobile/organizations/${org}/downloads/android`;
    const get=(url:string)=>app.inject({method:"GET",url,headers:{cookie}});
    assert.equal((await app.inject({method:"GET",url:config})).statusCode,401);
    assert.equal((await get(config)).statusCode,403, "Unset flags must hide downloads for existing and new companies");
    await platform.saveGlobal(org,{data:{app_flags:{mobile:{developer_downloads:true}}}});
    assert.equal((await get(config)).statusCode,403, "Testing downloads must not bypass the parent flag");
    await platform.saveGlobal(org,{data:{app_flags:{mobile:{app_download:true,developer_downloads:false}}}});
    const defaults=await get(config);assert.equal(defaults.statusCode,200,defaults.body);assert.equal(defaults.json().developer,null);assert.equal(defaults.headers["cache-control"],"private, no-store");
    assert.equal((await get(apk)).statusCode,403);
    assert.notEqual((await get("/v1/mobile/organizations/someone-else/config")).statusCode,200);
    await platform.saveGlobal(org,{data:{app_flags:{mobile:{app_download:true,developer_downloads:true}}}});
    assert.equal((await get(apk)).statusCode,404);
    const file=path.join(root,"test.apk");await writeFile(file,"test-artifact");process.env.MOBILE_ANDROID_TEST_APK_PATH=file;
    assert.equal((await get(config)).json().developer.android,apk);
    const binary=await get(apk);assert.equal(binary.statusCode,200);assert.equal(binary.body,"test-artifact");assert.match(String(binary.headers["content-disposition"]),/attachment/);
    process.env.FIRSTMEASURE_DATA_ENVIRONMENT="production";
    assert.equal(developmentDownloadsAllowed(),false);assert.equal((await get(config)).json().developer,null);assert.equal((await get(apk)).statusCode,403);
    process.env.FIRSTMEASURE_DATA_ENVIRONMENT="development";process.env.MOBILE_DEVELOPER_DOWNLOADS_ENABLED="0";
    assert.equal((await get(apk)).statusCode,403);
    await platform.saveGlobal(org,{data:{app_flags:{mobile:{app_download:false,developer_downloads:true}}}});
    assert.equal((await get(config)).statusCode,403);
    const verifier=randomBytes(32).toString('base64url'),challenge=createHash('sha256').update(verifier).digest('base64url'),state=randomBytes(32).toString('base64url');
    const csrf=decodeURIComponent(cookie.split('; ').find(v=>v.startsWith('fm_platform_session_csrf='))!.split('=')[1]!);
    const authorize=(headers:any)=>app.inject({method:'POST',url:'/v1/mobile/auth/authorize',headers,payload:{challenge,state}});
    assert.equal((await authorize({})).statusCode,401);assert.equal((await authorize({cookie})).statusCode,403);
    const browser=await app.inject({method:'GET',url:`/v1/mobile/auth/browser?challenge=${challenge}&state=${state}`});assert.equal(browser.statusCode,302);assert.match(String(browser.headers.location),/^\/portal\/login.php\?redirect=/);
    const approved=await authorize({cookie,'x-platform-csrf':csrf});assert.equal(approved.statusCode,200,approved.body);
    const callback=new URL(approved.json().callback);assert.equal(callback.protocol,'ai.firstmeasure.mobile.dev:');assert.equal(callback.searchParams.get('state'),state);
    const code=callback.searchParams.get('code')!;
    const exchange=(code:string,verifier:string)=>app.inject({method:'POST',url:'/v1/mobile/auth/exchange',payload:{code,verifier}});
    assert.equal((await exchange(code,randomBytes(32).toString('base64url'))).statusCode,401);
    const exchanged=await Promise.all([exchange(code,verifier),exchange(code,verifier)]);assert.deepEqual(exchanged.map(r=>r.statusCode).sort(),[303,401]);
    assert.ok(exchanged.find(r=>r.statusCode===303)?.headers['set-cookie']);
    assert.equal((await exchange(code,verifier)).statusCode,401);
    const revoked=await authorize({cookie,'x-platform-csrf':csrf});const revokedCode=new URL(revoked.json().callback).searchParams.get('code')!;
    const ticket=await platform.readAuthSession(revokedCode);await platform.upsertDocument(org,'users',{id:String(ticket.user_id),data:{status:'disabled'}},{replace:false});
    assert.equal((await exchange(revokedCode,verifier)).statusCode,403);
  } finally {await app.close();await(await import("../firstmeasure/project_index.js")).closeFirstMeasureProjectIndex();}
});
