import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

test("channels and calls preserve sequences, search, unread state and isolation on shared storage", async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), "platform-channels-store-"));
  const url = process.env.TEST_POSTGRES_URL;
  Object.assign(process.env, { FIRSTMATE_ENV: "test", PLATFORM_STORAGE_ROOT: root, CHANNELS_STORAGE_ROOT: root, CALLS_STORAGE_ROOT: root, FIRSTMEASURE_DATABASE_MODE: url ? "postgres" : "local", DATABASE_URL: url || "", POSTGRES_POOL_MAX: "1", POSTGRES_AUTO_MIGRATE: "false" });
  const store = await import("../channels/storage.js");
  const collaboration = await import("../channels/collaboration.js");
  const calls = await import("../calls/storage.js");
  const database = await import("../src/database/postgres.js");
  t.after(async () => { await store.closeChannelsDatabase(); await calls.closeCallsDatabase(); await database.closePostgresPools(); await rm(root, { recursive: true, force: true }); });
  const org = `channels_${randomUUID()}`;
  const channel = (await store.createChannelRecord({ organization_id: org, type: "public", name: "Roofing", created_by: "alice" }))!;
  const messages = await Promise.all(Array.from({ length: 20 }, (_, i) => store.createMessageRecord({ organization_id: org, channel_id: channel.id, author_id: "alice", text: `Roof measurement ${i}` })));
  assert.deepEqual(messages.map(message => message!.seq).sort((a,b) => a-b), Array.from({ length: 20 }, (_, i) => i+1));
  await assert.rejects(store.createMessageRecord({ organization_id: "another_org", channel_id: channel.id, author_id: "bob", text: "forbidden" }));
  assert.equal((await store.readChannelRecord(org, channel.id))!.message_seq, 20);
  assert.equal((await store.searchMessageRecords(org, "roof")).length, 20);
  assert.equal((await store.searchMessageRecords("another_org", "roof")).length, 0);
  await store.softDeleteMessageRecord(org, messages[0]!.id, "alice");
  assert.equal((await store.searchMessageRecords(org, "roof")).length, 19);
  await store.editMessageRecord(org, messages[1]!, { text: "Siding report", edited_by: "alice" });
  assert.equal((await store.searchMessageRecords(org, "siding")).length, 1);
  await store.restoreMessageRecord(org, messages[0]!.id);
  assert.equal((await store.searchMessageRecords(org, "roof")).length, 19);
  await Promise.all(Array.from({ length: 20 }, (_, i) => store.upsertReadState(org, channel.id, "alice", 20-i)));
  assert.equal((await store.readStateFor(channel.id, "alice")).last_read_seq, 20);
  await collaboration.saveSidebarSection(org, "alice", { title: "Favorites", channel_ids: [channel.id] });
  assert.equal((await collaboration.listSidebarSections(org, "alice")).length, 1);
  await store.upsertChannelMember({ organization_id: org, channel_id: channel.id, user_id: "alice" });
  await collaboration.markUnreadRecord(org, channel.id, "alice", 10);
  const operation = await collaboration.markAllReadRecords(org, "alice", [(await store.readChannelRecord(org, channel.id))!]);
  assert.equal((await store.readStateFor(channel.id, "alice")).manual_unread_seq, null);
  await collaboration.undoReadOperation(org, "alice", String(operation.operation_id));
  const scheduled = await collaboration.createScheduledRecord(org, "alice", { channel_id: channel.id, text: "Scheduled report", scheduled_at: new Date(0).toISOString() });
  const scheduledId = String(scheduled.id);
  const deliver = async () => (await store.createMessageRecord({ organization_id: org, channel_id: channel.id, author_id: "alice", text: "Scheduled report", client_msg_id: scheduledId })).id;
  await assert.rejects(collaboration.deliverScheduledRecord(scheduledId, async () => { await deliver(); throw new Error("worker terminated"); }), /worker terminated/);
  assert.equal(await store.findMessageByClientId(channel.id, "alice", scheduledId), null);
  assert.equal((await collaboration.listScheduledRecords(org, "alice"))[0]!.state, "scheduled");
  const delivered = await Promise.all(Array.from({ length: 12 }, () => collaboration.deliverScheduledRecord(scheduledId, deliver)));
  assert.equal(delivered.filter(Boolean).length, 1);
  assert.equal((await collaboration.listScheduledRecords(org, "alice"))[0]!.state, "sent");
  assert.equal((await store.getChannelsDatabase().prepare("SELECT * FROM channel_delivery_outbox WHERE scheduled_id=?").all(scheduledId)).length, 1);
  assert.equal((await store.readChannelRecord(org, channel.id))!.message_seq, 21);
  const rooms = await Promise.all(Array.from({ length: 12 }, () => calls.createRoomRecord({ organization_id: org, context_type: "channel", context_id: channel.id, provider: "local", started_by: "alice", recording_mode: "off", allow_video: true })));
  assert.equal(new Set(rooms.map(room => room.id)).size, 1);
  const roomId = String(rooms[0]!.id);
  await Promise.all(Array.from({ length: 10 }, (_, i) => calls.createSignalRecord(org, roomId, "sender", "offer", { i }, "receiver")));
  const signals = await calls.listSignalRecords(org, roomId, 0, "receiver");
  assert.equal(signals.length, 10);
  assert.equal((await calls.listSignalRecords(org, roomId, 0, "someone_else")).length, 0);
  await assert.rejects(calls.listSignalRecords("another_org", roomId, 0, "receiver"));
});
