import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

test("workflow plans, scope seeds and event claims remain atomic across concurrent requests", async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), "platform-work-store-"));
  const url = process.env.TEST_POSTGRES_URL;
  Object.assign(process.env, { FIRSTMATE_ENV: "test", PLATFORM_STORAGE_ROOT: root, FIRSTMEASURE_DATABASE_MODE: url ? "postgres" : "local", DATABASE_URL: url || "", POSTGRES_POOL_MAX: "1", POSTGRES_AUTO_MIGRATE: "false" });
  const store = await import("../work/storage.js");
  const scopes = await import("../scopes/storage.js");
  const postgres = await import("../src/database/postgres.js");
  t.after(async () => { await store.closeWorkDatabase(); await postgres.closePostgresPools(); await rm(root, { recursive: true, force: true }); });
  const org = `work_${randomUUID()}`;
  const plans = await Promise.all(Array.from({ length: 12 }, () => store.createPlanRecord({ organization_id: org, source_key: "one", title: "Shared plan", status: "pending" })));
  assert.equal(plans.filter(result => result.created).length, 1);
  const plan = plans[0]!.plan!;
  assert.equal(await store.readPlanRecord("another-org", String(plan.id)), null);
  await Promise.all(Array.from({ length: 12 }, () => scopes.ensureDefaultScopeTemplates(org)));
  const templates = await scopes.listScopeTemplates(org, "default");
  assert.ok(templates.length > 0);
  assert.equal(new Set(templates.map(template => template.id)).size, templates.length);
  const events = await Promise.all(Array.from({ length: 20 }, () => store.createEventRecord({ organization_id: org, type: "test.created", idempotency_key: "one", plan_id: plan.id })));
  assert.equal(events.filter(result => result.created).length, 1);
  const claimed = await Promise.all(Array.from({ length: 20 }, (_, i) => store.claimNextEvent(`worker_${i}`)));
  assert.equal(claimed.filter(Boolean).length, 1);
  const event = claimed.find(Boolean)!;
  assert.equal(event.status, "processing");
  const execution = await store.beginExecutionRecord({ organization_id: org, event_id: event.id, binding_id: "binding", automation: "test", lease_owner: event.lease_owner });
  assert.equal(execution.execute, true);
  await store.getWorkDatabase().prepare("UPDATE work_events SET lease_until=? WHERE id=?").run(new Date(Date.now() - 1000).toISOString(), String(event.id));
  const recovered = await store.claimNextEvent("recovery");
  assert.ok(recovered);
  assert.equal(await store.finishEventRecord(String(event.id), String(event.lease_owner)), false);
  assert.equal(await store.renewEventLease(String(event.id), String(event.lease_owner)), false);
  assert.equal(await store.renewEventLease(String(event.id), String(recovered.lease_owner)), true);
  const resumed = await store.beginExecutionRecord({ organization_id: org, event_id: event.id, binding_id: "binding", automation: "test", lease_owner: recovered.lease_owner });
  assert.equal(resumed.execute, true);
  await store.finishExecutionRecord(String(event.id), "binding", String(event.lease_owner), { stale: true });
  assert.equal((await store.listExecutionRecords(org))[0]!.status, "running");
  await store.finishExecutionRecord(String(event.id), "binding", String(recovered.lease_owner), { recovered: true });
  assert.equal((await store.listExecutionRecords(org))[0]!.status, "succeeded");
  await store.finishEventRecord(String(event.id), String(recovered.lease_owner));
  assert.equal((await store.readEventRecord(org, String(event.id)))!.status, "completed");
  await assert.rejects(store.getWorkDatabase().transaction(async () => {
    await store.createPlanRecord({ organization_id: org, source_key: "rollback", title: "rollback", status: "pending" });
    throw new Error("rollback");
  }), /rollback/);
  assert.equal((await store.listPlanRecords(org)).length, 1);
});
