import { PDFDocument } from "pdf-lib";

export const FIRSTMATE_PDF_AUTHOR = "FirstMate";
export const FIRSTMATE_PDF_CREATOR = "FirstMate";
export const FIRSTMATE_PDF_PRODUCER = "FirstMate";

export type FirstMatePdfMetadata = {
  title?: string;
  subject?: string;
  keywords?: string[];
  creationDate?: Date | string;
  modificationDate?: Date | string;
};

function cleanText(value: unknown) {
  return String(value ?? "").trim();
}

function validDate(value: Date | string | undefined, fallback: Date) {
  const candidate = value instanceof Date ? new Date(value.getTime()) : value ? new Date(value) : fallback;
  return Number.isFinite(candidate.getTime()) ? candidate : fallback;
}

export function firstMatePdfDateString(value: Date | string = new Date()) {
  const date = validDate(value, new Date());
  const pad = (part: number) => String(part).padStart(2, "0");
  return `D:${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}+00'00'`;
}

export function setFirstMatePdfMetadata(doc: PDFDocument, metadata: FirstMatePdfMetadata = {}) {
  const generatedAt = validDate(metadata.creationDate, new Date());
  const modifiedAt = validDate(metadata.modificationDate, generatedAt);
  const title = cleanText(metadata.title) || "FirstMate Document";
  const subject = cleanText(metadata.subject) || "Document generated by FirstMate";
  const keywords = Array.from(new Set([
    FIRSTMATE_PDF_AUTHOR,
    ...(metadata.keywords ?? []).map(cleanText).filter(Boolean)
  ]));

  doc.setTitle(title);
  doc.setAuthor(FIRSTMATE_PDF_AUTHOR);
  doc.setCreator(FIRSTMATE_PDF_CREATOR);
  doc.setProducer(FIRSTMATE_PDF_PRODUCER);
  doc.setSubject(subject);
  doc.setKeywords(keywords);
  doc.setCreationDate(generatedAt);
  doc.setModificationDate(modifiedAt);
  return doc;
}

export async function finalizeFirstMatePdf(
  bytes: Uint8Array,
  metadata: FirstMatePdfMetadata = {}
) {
  const doc = await PDFDocument.load(bytes, { updateMetadata: false });
  setFirstMatePdfMetadata(doc, metadata);
  return Buffer.from(await doc.save());
}
