import { z } from 'zod';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { payrollPayeeRefSchema, payrollPolicySubjectSchema } from './schemas.js';

const text=z.string(), cents=z.number().int(), json=z.record(z.unknown());
const object=(fields:Record<string,z.ZodTypeAny>)=>z.object(fields).passthrough();
export const payeeSchema=object({type:z.enum(['organization_user','organization_connection']),id:text,name:text,worker_type:text});
export const ledgerSchema=object({id:text,organization_id:text,payee:payeeSchema,schedule_id:text,kind:text,subgroup:text,state:text,amount_cents:cents,applied_cents:cents,remaining_cents:cents,currency:text,project_id:text,project_title:text,worked_at:text,completed_at:text,eligible_at:text,source_event_id:text,source_trigger_id:text,description:text,metadata:json,revision:cents,created_at:text,updated_at:text,voided_at:text});
export const scheduleSchema=object({id:text,organization_id:text,name:text,status:text,currency:text,timezone:text,recurrence:object({frequency:text,weekday:cents.optional(),days:z.array(cents).optional(),day:cents.optional(),anchor_date:text.optional()}),delay:object({periods:cents.optional(),days:cents.optional()}),timing_basis:text,clawback_cap_percent:z.number(),revision:cents,metadata:json,created_at:text,updated_at:text,archived_at:text});
export const policySchema=object({subject_type:text,subject_id:text,schedule_id:text,earning_kind:text,revision:cents});
export const roleSchema=object({project_id:text,role_key:text,label:text,payees:z.array(payrollPayeeRefSchema),revision:cents,metadata:json});
export const itemSchema=object({id:text,batch_id:text,payee:payeeSchema,status:text,gross_cents:cents,commission_cents:cents,deduction_cents:cents,net_cents:cents,subgroup_totals:z.record(cents),payment_reference:text,entries:z.array(ledgerSchema),revision:cents,run_at:text,paid_at:text});
export const batchSchema=object({id:text,organization_id:text,schedule_id:text,pay_date:text,period_start:text,period_end:text,status:text,currency:text,total_cents:cents,employee_total_cents:cents,subcontractor_total_cents:cents,run_type:text,approval:json,metadata:json,revision:cents,items:z.array(itemSchema),created_at:text,updated_at:text,run_at:text,paid_at:text,voided_at:text});
export const artifactSchema=object({id:text,batch_id:text,artifact_type:text,report_type:text,file_name:text,content_type:text,size_bytes:cents,metadata:json,created_at:text,download_url:text.optional()});
const preview=object({payee:payeeSchema.optional(),worker_type:text.optional(),gross_cents:cents,deduction_cents:cents,net_cents:cents,subgroup_totals:z.record(cents),entry_count:cents});
const occurrence=object({schedule:scheduleSchema,pay_date:text,cutoff_at:text,batch:batchSchema.nullable(),employees:z.array(object({payee:payeeSchema,accrued:preview,projected:preview,forecast_net_cents:cents})),subcontractors:z.array(object({payee:payeeSchema,accrued:preview,projected:preview,forecast_net_cents:cents})),accrued_total_cents:cents,projected_additional_cents:cents,forecast_total_cents:cents});
export const upcomingSchema=object({from:text,through:text,schedules:z.array(scheduleSchema),upcoming:z.array(occurrence),diagnostics:z.array(object({code:text}))});
export const dashboardSchema=upcomingSchema.extend({policies:z.array(policySchema),history:z.array(batchSchema)});
const totals=object({projected_cents:cents,accrued_cents:cents,in_payroll_cents:cents,owed_cents:cents,paid_cents:cents,earned_cents:cents});
export const earningsSchema=object({earnings:z.array(object({subject:payeeSchema,currency:text,totals,projects:z.array(object({project_id:text,title:text,currency:text,totals})),entries:z.array(object({id:text,state:text,kind:text,amount_cents:cents,remaining_cents:cents,eligible_at:text})),payments:z.array(object({id:text,batch_id:text,status:text,pay_date:text,net_cents:cents,allocations:z.array(object({ledger_entry_id:text,amount_cents:cents,project_id:text}))}))})),count:cents,filters:json,truncated:z.boolean(),entries_truncated:z.boolean(),payments_truncated:z.boolean()});
export const timesheetSchema=object({id:text,user_id:text,project_id:text,status:text,worked_seconds:z.number(),timesheet:json.optional()});
export const timesheetsSchema=object({timesheets:z.array(timesheetSchema),count:cents});
export const exportCatalogSchema=z.array(object({type:text,label:text,description:text,purpose:text,scope:text,scope_label:text,formats:z.array(text)}));
export const contractorSchema=object({users:z.array(object({id:text,name:text,worker_classification:text,payment_terms:json})),connections:z.array(object({id:text,name:text,payment_terms:json}))});
export const configurationSchema=object({schedules:z.array(scheduleSchema),policies:z.array(policySchema)});
export const querySchema=z.object({from:text.optional(),through:text.optional(),include_projected:z.boolean().optional(),history_limit:z.number().int().min(1).max(500).optional(),limit:z.number().int().min(1).max(5000).optional(),project_id:text.optional(),schedule_id:text.optional(),state:text.optional(),kind:text.optional(),payee_id:text.optional(),payee_type:z.enum(['organization_user','organization_connection']).optional(),source_event_id:text.optional(),eligible_from:text.optional(),eligible_through:text.optional(),open_only:z.boolean().optional(),status:text.optional(),user_id:text.optional(),approval_status:text.optional(),batch_id:text.optional(),artifact_type:text.optional(),report_type:text.optional(),include_archived:z.boolean().optional(),entry_limit:z.number().int().min(1).max(5000).optional(),payment_limit:z.number().int().min(1).max(500).optional(),payees:z.array(payrollPayeeRefSchema).max(100).optional()}).strict();
export const effectivePolicyInput=z.object({payee:payrollPayeeRefSchema,earning_kind:text.optional()}).strict();
export const policySaveInput=z.object({subject_type:payrollPolicySubjectSchema,subject_id:text.min(1),values:json}).strict();
export function jsonSchema(schema:z.ZodTypeAny){return zodToJsonSchema(schema,{$refStrategy:'none'}) as Record<string,unknown>;}
