import { registerDataProvider } from "../platform/publication/providers.js";
import { registerAction } from "../platform/publication/actions.js";
import { backendImplementationDigest } from "../platform/publication/implementation.js";
import { contactOptions, contactSettings, saveContactSettings } from "./service.js";
import { normalizeContactSettings } from "./contracts.js";
let registered=false;
export function registerContactPublication(){
 if(registered)return;registered=true;
 const access={scopes:["organization"] as const,permissions:["view_contacts"],systemKinds:["work","module","agent"] as const};
 registerDataProvider({id:"contacts",version:"1",apps:["contacts"],exports:{
  settings:{schema:{type:"object",required:["version","tags","track_time_zones"],properties:{version:{type:"integer"},track_time_zones:{type:"boolean"},tags:{type:"array",items:{type:"object",required:["id","label","enabled"],properties:{id:{type:"string"},label:{type:"string"},enabled:{type:"boolean"},builtin:{type:"boolean"}},additionalProperties:false}}},additionalProperties:false},schemaVersion:"2",access:{...access,scopes:[...access.scopes],systemKinds:[...access.systemKinds]},description:"Managed contact tags and organization time-zone preference.",read:async ctx=>({value:await contactSettings(ctx.organizationId)})},
  options:{schema:{type:"array",items:{type:"object",required:["contact_id","project_id","name","contact_kind"],properties:{contact_id:{type:"string"},project_id:{type:"string"},name:{type:"string"},contact_kind:{enum:["human","org"]}},additionalProperties:false}},schemaVersion:"1",argsSchema:{type:"object",properties:{kind:{enum:["human","org","either"]}},additionalProperties:false},access:{...access,scopes:[...access.scopes],systemKinds:[...access.systemKinds]},description:"Saved contacts eligible for typed relationship fields.",read:async(ctx,ref)=>({value:await contactOptions(ctx.organizationId,String(ref.args?.kind || "either"))})}
 }});
 registerAction({id:"contacts.settings.save",version:"1",implementation:backendImplementationDigest(),domain:"contacts",description:"Manage contact tags and the time-zone preference.",inputSchema:{type:"object",required:["tags"],properties:{track_time_zones:{type:"boolean"},tags:{type:"array",maxItems:257,items:{type:"object",required:["id","label"],properties:{id:{type:"string",maxLength:64},label:{type:"string",maxLength:80},enabled:{type:"boolean"},builtin:{type:"boolean"}},additionalProperties:false}}},additionalProperties:false},outputSchema:{type:"object",required:["version","tags","track_time_zones"],properties:{version:{type:"integer"},track_time_zones:{type:"boolean"},tags:{type:"array",items:{type:"object"}}},additionalProperties:false},policy:{scopes:["organization"],permissions:["manage_company_settings"],systemKinds:["work","module","agent"]},effect:"write",executionKinds:["api","agent","module","work"],idempotency:"required",validateInput:input=>{normalizeContactSettings(input);},execute:(ctx,_target,input)=>saveContactSettings(ctx.organizationId,input)});
}
